import { z } from 'zod';

/**
 * ─ Ambient dashboard ────────────────────────────────────────────────
 *
 * The opt-in background job where the meester composes a squisq
 * dashboard document (6-9 short markdown blocks) summarizing the whole
 * workshop and renders it to a single PNG. Generated by
 * `packages/service/src/ambient/dashboard-generator.ts`, written under
 * `~/.gezel/ambient/` (dated files + a stable `latest.png`), and served
 * over `GET /api/ambient-dashboard`. The PNGs feed the OS ambient
 * display integration — wallpaper / lock-screen rotation.
 */

/**
 * Squisq dashboard resolution preset ids. Mirrors squisq-video's
 * DASHBOARD_RESOLUTIONS — core cannot depend on squisq, so keep in sync
 * with that catalog (guarded by a service-side test against the real
 * export).
 */
export const AmbientDashboardResolutionSchema = z.enum([
  'hd',
  'fhd',
  '4k',
  'square',
  'square-2k',
  'portrait',
  'portrait-4k',
  'standard',
]);
export type AmbientDashboardResolution = z.infer<typeof AmbientDashboardResolutionSchema>;

/** Squisq dashboard cell styles. Same keep-in-sync note as resolutions. */
export const AmbientDashboardStyleSchema = z.enum(['basic', 'card', 'panel', 'accent']);
export type AmbientDashboardStyle = z.infer<typeof AmbientDashboardStyleSchema>;

/**
 * `~/.gezel/ambient/state.json` — throttle + idempotency. A failed run
 * still advances `lastRunAt` (chronic failure must not retry every
 * sweep) but keeps the previous `inputHash` so the next allowed run
 * retries the same input.
 */
export const AmbientDashboardStateSchema = z.object({
  lastRunAt: z.string().optional(),
  inputHash: z.string().optional(),
  /** Filename (not path) of the newest dated PNG, e.g. `dashboard-20260817-1400.png`. */
  lastFile: z.string().optional(),
});
export type AmbientDashboardState = z.infer<typeof AmbientDashboardStateSchema>;

/** Wire shape for `GET /api/ambient-dashboard`. */
export const AmbientDashboardStatusResponseSchema = z.object({
  enabled: z.boolean(),
  running: z.boolean(),
  lastGeneratedAt: z.string().nullable(),
  latestFilename: z.string().nullable(),
  resolution: AmbientDashboardResolutionSchema,
});
export type AmbientDashboardStatusResponse = z.infer<typeof AmbientDashboardStatusResponseSchema>;
