import { z } from 'zod';

/**
 * ─ Ambient dashboard ────────────────────────────────────────────────
 *
 * The opt-in background job where the meester composes a squisq
 * dashboard document (6-9 short markdown blocks) summarizing the whole
 * workshop and renders it to a single PNG. Generated by
 * `packages/service/src/ambient/dashboard-generator.ts`, written under
 * `~/.gezel/ambient/` (dated files + a stable `latest.png`), and served
 * over `GET /api/ambient-dashboard`. The PNGs feed the OS ambient
 * display integration — wallpaper / lock-screen rotation.
 */

/**
 * Squisq dashboard resolution preset ids. Mirrors squisq-video's
 * DASHBOARD_RESOLUTIONS — core cannot depend on squisq, so keep in sync
 * with that catalog (guarded by a service-side test against the real
 * export).
 */
export const AmbientDashboardResolutionSchema = z.enum([
  'hd',
  'fhd',
  '4k',
  'square',
  'square-2k',
  'portrait',
  'portrait-4k',
  'standard',
]);
export type AmbientDashboardResolution = z.infer<typeof AmbientDashboardResolutionSchema>;

/** Squisq dashboard cell styles. Same keep-in-sync note as resolutions. */
export const AmbientDashboardStyleSchema = z.enum(['basic', 'card', 'panel', 'accent']);
export type AmbientDashboardStyle = z.infer<typeof AmbientDashboardStyleSchema>;

/**
 * Built-in Squisq theme ids. Mirrors squisq's theme catalog — core cannot
 * depend on squisq, so a service-side test guards this list against the real
 * export. The selected id is persisted in config; human-readable catalog
 * metadata comes from the daemon rather than being duplicated here.
 */
export const AmbientDashboardThemeSchema = z.enum([
  'standard',
  'standard-dark',
  'documentary',
  'minimalist',
  'bold',
  'morning-light',
  'tech-dark',
  'magazine',
  'cinematic',
  'warm-earth',
  'gezellig',
]);
export type AmbientDashboardTheme = z.infer<typeof AmbientDashboardThemeSchema>;

export const AmbientDashboardThemeSummarySchema = z.object({
  id: AmbientDashboardThemeSchema,
  name: z.string(),
  description: z.string(),
});
export type AmbientDashboardThemeSummary = z.infer<typeof AmbientDashboardThemeSummarySchema>;

/**
 * Custom dashboard-image limits. These mirror squisq-video's PNG export
 * validator. Keeping them here lets the Electron shell reject an impossible
 * display target before persisting it for a later background render.
 */
export const AMBIENT_DASHBOARD_MIN_DIMENSION = 64;
export const AMBIENT_DASHBOARD_MAX_DIMENSION = 7_680;
export const AMBIENT_DASHBOARD_MAX_PIXELS = 33_177_600;

/**
 * The physical-pixel canvas and usable content rectangle for the primary
 * display. `safeArea` is derived from the OS work area, with a small breathing
 * margin, so menu bars, notches, docks, and taskbars do not cover dashboard
 * content. The surrounding canvas remains full-screen-sized so Fill/Zoom
 * wallpaper modes do not crop the dashboard to reconcile aspect ratios.
 */
export const AmbientDashboardDisplayTargetSchema = z
  .object({
    width: z
      .number()
      .int()
      .min(AMBIENT_DASHBOARD_MIN_DIMENSION)
      .max(AMBIENT_DASHBOARD_MAX_DIMENSION),
    height: z
      .number()
      .int()
      .min(AMBIENT_DASHBOARD_MIN_DIMENSION)
      .max(AMBIENT_DASHBOARD_MAX_DIMENSION),
    safeArea: z.object({
      x: z.number().int().nonnegative(),
      y: z.number().int().nonnegative(),
      width: z
        .number()
        .int()
        .min(AMBIENT_DASHBOARD_MIN_DIMENSION)
        .max(AMBIENT_DASHBOARD_MAX_DIMENSION),
      height: z
        .number()
        .int()
        .min(AMBIENT_DASHBOARD_MIN_DIMENSION)
        .max(AMBIENT_DASHBOARD_MAX_DIMENSION),
    }),
  })
  .superRefine((target, ctx) => {
    if (target.width * target.height > AMBIENT_DASHBOARD_MAX_PIXELS) {
      ctx.addIssue({
        code: 'custom',
        message: `The dashboard display target may not exceed ${AMBIENT_DASHBOARD_MAX_PIXELS} pixels.`,
      });
    }
    if (target.safeArea.x + target.safeArea.width > target.width) {
      ctx.addIssue({
        code: 'custom',
        path: ['safeArea', 'width'],
        message: 'The safe area must fit inside the display width.',
      });
    }
    if (target.safeArea.y + target.safeArea.height > target.height) {
      ctx.addIssue({
        code: 'custom',
        path: ['safeArea', 'height'],
        message: 'The safe area must fit inside the display height.',
      });
    }
  });
export type AmbientDashboardDisplayTarget = z.infer<typeof AmbientDashboardDisplayTargetSchema>;

/**
 * `~/.gezel/ambient/state.json` — throttle + idempotency. A failed run
 * still advances `lastRunAt` (chronic failure must not retry every
 * sweep) but keeps the previous `inputHash` so the next allowed run
 * retries the same input.
 */
export const AmbientDashboardStateSchema = z.object({
  /** Most recent attempt, successful or not. Used for automatic-run throttling. */
  lastRunAt: z.string().optional(),
  /** Most recent successful PNG render. Kept separate so failed attempts cannot masquerade as output. */
  lastGeneratedAt: z.string().optional(),
  /** Most recent failed attempt and its user-facing reason. Cleared by the next successful render. */
  lastFailedAt: z.string().optional(),
  lastError: z.string().optional(),
  inputHash: z.string().optional(),
  /** Filename (not path) of the newest dated PNG, e.g. `dashboard-20260817-1400.png`. */
  lastFile: z.string().optional(),
});
export type AmbientDashboardState = z.infer<typeof AmbientDashboardStateSchema>;

/** Wire shape for `GET /api/ambient-dashboard`. */
export const AmbientDashboardStatusResponseSchema = z.object({
  enabled: z.boolean(),
  running: z.boolean(),
  lastGeneratedAt: z.string().nullable(),
  /** Latest failed attempt. Optional for compatibility with older daemons. */
  lastFailedAt: z.string().nullable().optional(),
  lastError: z.string().nullable().optional(),
  latestFilename: z.string().nullable(),
  resolution: AmbientDashboardResolutionSchema,
  /** Squisq theme selected for the next render. Optional for older daemons. */
  themeId: AmbientDashboardThemeSchema.optional(),
  /** Live built-in catalog for Settings. Optional for older daemons. */
  themes: z.array(AmbientDashboardThemeSummarySchema).optional(),
  /** Exact primary-display target when the Electron shell has reported one. */
  displayTarget: AmbientDashboardDisplayTargetSchema.nullable().optional(),
});
export type AmbientDashboardStatusResponse = z.infer<typeof AmbientDashboardStatusResponseSchema>;
