import { z } from 'zod';
import { PoppetjeSchema } from '../poppetje/schema.js';

/**
 * Wire schemas for the Handboek — gezel's built-in documentation.
 *
 * Articles are squisq-flavored markdown assembled by the service-side
 * handboek engine from hand-curated segments (shipped from the repo's
 * `docs/handboek/` tree) and autogenerated bodies (catalog craftbooks,
 * project types, role registry). Autoannotation macros
 * (`::handboek-<name>{…}` leaf directives) are expanded server-side
 * into plain markdown before an article ever reaches a renderer, so
 * the UI, the video player, and the static-site export all consume the
 * same shape.
 */

export const HandboekAreaSchema = z.enum([
  'conceptual',
  'gezel-roles',
  'craftbooks',
  'project-types',
  'technical',
  'whats-new',
]);
export type HandboekArea = z.infer<typeof HandboekAreaSchema>;

/**
 * How an article is rendered:
 * - `app`   — personalized for this install (gezel rosters, installed
 *             models, device-tailored tool tables, poppetje figures).
 * - `site`  — generic, no personal data; the CLI static-site export.
 * - `agent` — AI-tailored: compact, no figures; backs the `how_do_i`
 *             MCP tool.
 */
export const HandboekRenderModeSchema = z.enum(['app', 'site', 'agent']);
export type HandboekRenderMode = z.infer<typeof HandboekRenderModeSchema>;

/** Optional nested shelf used to organize entries inside a TOC area. */
export const HandboekTocSubcategorySchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  order: z.number(),
});
export type HandboekTocSubcategory = z.infer<typeof HandboekTocSubcategorySchema>;

export const HandboekTocEntrySchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  area: HandboekAreaSchema,
  /** Sort key within the area. Curated articles set it via frontmatter. */
  order: z.number(),
  summary: z.string().optional(),
  /** Poster headline for the page's Open Graph card, when the author set one. */
  ogHeadline: z.string().optional(),
  /** True for articles whose body is produced from catalog/registry data. */
  generated: z.boolean(),
  /** False when the article is excluded from the static-site export. */
  siteVisible: z.boolean().optional(),
  /** Optional collapsible shelf within the entry's broader area. */
  subcategory: HandboekTocSubcategorySchema.optional(),
});
export type HandboekTocEntry = z.infer<typeof HandboekTocEntrySchema>;

export const HandboekTocAreaSchema = z.object({
  area: HandboekAreaSchema,
  title: z.string(),
  entries: z.array(HandboekTocEntrySchema),
});
export type HandboekTocArea = z.infer<typeof HandboekTocAreaSchema>;

export const HandboekTocSchema = z.object({
  areas: z.array(HandboekTocAreaSchema),
});
export type HandboekToc = z.infer<typeof HandboekTocSchema>;

/**
 * A poppetje figure referenced by an article. The expanded markdown
 * embeds the figure as a relative image (`poppetje/{gezelId}.{variant}.svg`);
 * this payload carries the struct so the UI's media provider can render
 * the SVG client-side without extra fetches.
 */
export const HandboekFigureSchema = z.object({
  /** The relative path used in the markdown image reference. */
  path: z.string().min(1),
  gezelId: z.string().min(1),
  name: z.string(),
  roleLabel: z.string().optional(),
  variant: z.enum(['full', 'headshot', 'icon']),
  poppetje: PoppetjeSchema,
});
export type HandboekFigure = z.infer<typeof HandboekFigureSchema>;

/**
 * One narration audio segment. Segments are returned in doc-block
 * order, exactly one per block — text-less blocks get a short silent
 * segment — so the player can map block i to segment i positionally.
 */
export const HandboekNarrationSegmentSchema = z.object({
  blockId: z.string(),
  /** Cache key; fetch the WAV via `/api/handboek/narration/audio/:hash`. */
  hash: z.string().regex(/^[a-f0-9]{64}$/),
  durationMs: z.number().int().nonnegative(),
  silent: z.boolean().optional(),
});
export type HandboekNarrationSegment = z.infer<typeof HandboekNarrationSegmentSchema>;

export const HandboekNarrationResponseSchema = z.object({
  articleId: z.string(),
  voice: z.string(),
  model: z.string(),
  segments: z.array(HandboekNarrationSegmentSchema),
});
export type HandboekNarrationResponse = z.infer<typeof HandboekNarrationResponseSchema>;

export const HandboekArticleSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  area: HandboekAreaSchema,
  summary: z.string().optional(),
  /** Squisq-flavored markdown with all handboek macros already expanded. */
  markdown: z.string(),
  figures: z.array(HandboekFigureSchema).default([]),
  generated: z.boolean(),
  /** Per-block seconds for the video playback mode's synthetic clock. */
  defaultDuration: z.number().positive().optional(),
});
export type HandboekArticle = z.infer<typeof HandboekArticleSchema>;

/** `how_do_i` answers: best-matching articles, rendered in agent mode. */
export const HandboekHowDoIResponseSchema = z.object({
  results: z.array(HandboekArticleSchema),
});
export type HandboekHowDoIResponse = z.infer<typeof HandboekHowDoIResponseSchema>;
