import { z } from 'zod';

/**
 * ─ Meester status report ────────────────────────────────────────────
 *
 * The occasional background job where the meester surveys every active
 * project and writes the Home greeting: a short headline with a
 * call-to-action, a markdown dashboard report (rendered with squisq),
 * and up to a few follow-up actions materialized as draft tasks.
 * Generated by `packages/service/src/meester/status-generator.ts`,
 * persisted under `~/.gezel/meester-status/` via the Store, and served
 * over `GET /api/meester-status`.
 */

export const MEESTER_STATUS_HEADLINE_MAX = 120;

/**
 * Where a click on the headline lands. Targets are validated against
 * the live install before persisting — a CTA pointing at a deleted
 * project or task is dropped rather than rendered dead.
 */
export const MeesterStatusCtaSchema = z.object({
  label: z.string().max(60),
  target: z.discriminatedUnion('kind', [
    z.object({ kind: z.literal('project'), projectId: z.string() }),
    z.object({ kind: z.literal('task'), projectId: z.string(), taskRef: z.string() }),
    z.object({
      kind: z.literal('view'),
      view: z.enum(['projects', 'gezels', 'documents', 'settings']),
    }),
  ]),
});
export type MeesterStatusCta = z.infer<typeof MeesterStatusCtaSchema>;

/** A follow-up the meester proposed, already materialized as a draft task. */
export const MeesterStatusActionSchema = z.object({
  projectId: z.string(),
  /** `projectId/num` ref of the draft task created for this action. */
  taskRef: z.string(),
  title: z.string(),
});
export type MeesterStatusAction = z.infer<typeof MeesterStatusActionSchema>;

/** `~/.gezel/meester-status/status.json` — the current report. */
export const MeesterStatusReportSchema = z.object({
  headline: z.string().max(MEESTER_STATUS_HEADLINE_MAX),
  cta: MeesterStatusCtaSchema.optional(),
  /** Markdown dashboard body, rendered with squisq LinearDocView. */
  report: z.string(),
  generatedAt: z.string(),
  trigger: z.enum(['auto', 'manual']),
  actions: z.array(MeesterStatusActionSchema).default([]),
});
export type MeesterStatusReport = z.infer<typeof MeesterStatusReportSchema>;

/**
 * What the model itself returns inside its single ```json fence. The
 * service stamps `generatedAt`/`trigger` and swaps proposed `actions`
 * for materialized task refs before persisting as a report.
 */
export const MeesterStatusModelOutputSchema = z.object({
  headline: z.string(),
  cta: MeesterStatusCtaSchema.optional(),
  report: z.string(),
  actions: z
    .array(
      z.object({
        projectId: z.string(),
        title: z.string(),
        description: z.string(),
      }),
    )
    .optional(),
});
export type MeesterStatusModelOutput = z.infer<typeof MeesterStatusModelOutputSchema>;

/**
 * `~/.gezel/meester-status/state.json` — run budget + idempotency.
 * `runDay` is a local-calendar `YYYY-MM-DD` so the daily budget resets
 * at the user's midnight, not UTC's. `recentActionKeys` is a bounded
 * ring of sha256(projectId + normalized title) so a follow-up the user
 * already completed (or dismissed) isn't re-drafted on the next run.
 */
export const MeesterStatusStateSchema = z.object({
  lastRunAt: z.string().optional(),
  inputHash: z.string().optional(),
  runDay: z.string().optional(),
  runsOnDay: z.number().int().nonnegative().optional(),
  recentActionKeys: z.array(z.string()).optional(),
});
export type MeesterStatusState = z.infer<typeof MeesterStatusStateSchema>;

/**
 * `~/.gezel/projects/{id}/activity.json` — the project's last observed
 * activity (chat turns + history-logged mutations), maintained by the
 * ActivityTracker. Deliberately separate from `project.json`: this is a
 * high-frequency ambient stamp and must never contend with (or bump)
 * `project.updatedAt`.
 */
export const ProjectActivitySchema = z.object({
  lastActivityAt: z.string(),
});
export type ProjectActivity = z.infer<typeof ProjectActivitySchema>;

/** Wire shape for `GET /api/meester-status`. */
export const MeesterStatusResponseSchema = z.object({
  report: MeesterStatusReportSchema.nullable(),
  budget: z.object({
    runsToday: z.number().int().nonnegative(),
    maxRunsPerDay: z.number().int().positive(),
    lastRunAt: z.string().nullable(),
  }),
  running: z.boolean(),
});
export type MeesterStatusResponse = z.infer<typeof MeesterStatusResponseSchema>;
