import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Minimal template seeded into an internal project workspace on first
 * creation. Gives the gezels a familiar Node + TypeScript baseline
 * (package.json with type: module, tsconfig tuned for Node 22's native
 * strip-types, and a .gitignore for node_modules) without prescribing
 * any bundler or test framework. Teams that need more add tooling via
 * `npm_install` or edit the files directly — the template is never
 * re-applied after creation, so it can't clobber user changes.
 *
 * Skipped entirely when the project has an external `workingDir` —
 * that's the user's repo with its own tooling, and we must not touch
 * it.
 */
export interface BootstrapWorkspaceOptions {
  workspaceDir: string;
  projectId: string;
  projectName?: string;
}

const TSCONFIG = {
  compilerOptions: {
    target: 'es2023',
    module: 'NodeNext',
    moduleResolution: 'NodeNext',
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    allowImportingTsExtensions: true,
    noEmit: true,
  },
};

const GITIGNORE = `# Gezel workspace — autogenerated defaults
node_modules/
dist/
build/
.cache/
*.log
.DS_Store
`;

/**
 * Idempotent: each file is only created if missing, so re-running the
 * bootstrap (e.g. after a user deletes package.json) never overwrites
 * something the user or a gezel has customized. Returns the set of
 * filenames that were actually written.
 */
export async function bootstrapWorkspace(opts: BootstrapWorkspaceOptions): Promise<string[]> {
  const { workspaceDir, projectId, projectName } = opts;
  await mkdir(workspaceDir, { recursive: true });
  const written: string[] = [];

  const pkgJsonPath = join(workspaceDir, 'package.json');
  if (!existsSync(pkgJsonPath)) {
    const pkg = {
      name: slugifyForPackageName(projectName ?? projectId),
      private: true,
      version: '0.0.0',
      type: 'module',
      engines: { node: '>=24.0.0' },
    };
    await writeFile(pkgJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
    written.push('package.json');
  }

  const tsConfigPath = join(workspaceDir, 'tsconfig.json');
  if (!existsSync(tsConfigPath)) {
    await writeFile(tsConfigPath, `${JSON.stringify(TSCONFIG, null, 2)}\n`, 'utf8');
    written.push('tsconfig.json');
  }

  const gitignorePath = join(workspaceDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    await writeFile(gitignorePath, GITIGNORE, 'utf8');
    written.push('.gitignore');
  }

  return written;
}

/**
 * npm package names must be lowercase, URL-safe, and start with a
 * letter or digit. Project ids are already slug-ish but may contain
 * characters npm rejects (spaces, slashes for scoped names we don't
 * want to leak). Fall back to `gezel-workspace` when the result would
 * be empty.
 */
function slugifyForPackageName(raw: string): string {
  const cleaned = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/^\./, '')
    .slice(0, 214);
  return cleaned || 'gezel-workspace';
}
