import { z } from 'zod';

/**
 * Craftbook subject categories — *what kind of work is this recipe about?*
 *
 * This is a third axis, deliberately independent of the two that already
 * exist. `CraftbookRole` answers "where in a project's life does this fit?"
 * (starter / maintenance / general) and a project type's `craftbookTags`
 * answer "does this fit THIS project?". Neither of those splits a 250-book
 * catalog into shelves a person can browse: on a code project the role axis
 * collapses to two enormous piles, one of which ("General work") is mostly
 * recipes about writing, media, and household admin.
 *
 * Each category belongs to a family — `code`, `non-code`, or the `universal`
 * shelves that belong to neither — so a browser can separate "recipes for
 * working on software" from everything else with one grouping, then offer a
 * real breakdown inside each.
 */
export const CraftbookCategorySchema = z.enum([
  'code-build',
  'code-quality',
  'code-review',
  'code-data',
  'code-release',
  'code-ops',
  'code-docs',
  'writing',
  'media',
  'design',
  'marketing',
  'research',
  'business',
  'personal',
  'practice',
  'other',
]);
export type CraftbookCategory = z.infer<typeof CraftbookCategorySchema>;

export type CraftbookCategoryFamily = 'code' | 'non-code' | 'universal';

/** Shelf copy so every craftbook browser presents categories consistently. */
export const CRAFTBOOK_CATEGORY_META: ReadonlyArray<{
  id: CraftbookCategory;
  family: CraftbookCategoryFamily;
  label: string;
  description: string;
}> = [
  {
    id: 'code-build',
    family: 'code',
    label: 'Build & features',
    description: 'scaffold apps, pages, games, and features from scratch',
  },
  {
    id: 'code-quality',
    family: 'code',
    label: 'Testing & fixes',
    description: 'tests, coverage, refactors, bug hunts, and performance work',
  },
  {
    id: 'code-review',
    family: 'code',
    label: 'Review & security',
    description: 'code review, security and dependency audits, accessibility passes',
  },
  {
    id: 'code-data',
    family: 'code',
    label: 'APIs & data',
    description: 'endpoints, schemas, pipelines, scrapers, and integrations',
  },
  {
    id: 'code-release',
    family: 'code',
    label: 'Release & deploy',
    description: 'changelogs, versioning, CI, containers, rollouts, and rollbacks',
  },
  {
    id: 'code-ops',
    family: 'code',
    label: 'Running it',
    description: 'monitoring, alerting, incidents, runbooks, and scheduled jobs',
  },
  {
    id: 'code-docs',
    family: 'code',
    label: 'Developer docs',
    description: 'reference docs, specs, and keeping documentation honest',
  },
  {
    id: 'writing',
    family: 'non-code',
    label: 'Writing & editing',
    description: 'drafts, edits, translations, handbooks, and long-form prose',
  },
  {
    id: 'media',
    family: 'non-code',
    label: 'Images, audio & video',
    description: 'generate, transcribe, edit, and organise media',
  },
  {
    id: 'design',
    family: 'non-code',
    label: 'Design & print',
    description: 'visual identity, UI critique, decks, and printable layouts',
  },
  {
    id: 'marketing',
    family: 'non-code',
    label: 'Marketing & sales',
    description: 'campaigns, copy, social posts, launches, and pitches',
  },
  {
    id: 'research',
    family: 'non-code',
    label: 'Research & analysis',
    description: 'gather sources, check facts, compare options, read the numbers',
  },
  {
    id: 'business',
    family: 'non-code',
    label: 'Business & admin',
    description: 'money, meetings, contracts, careers, and the recurring paperwork',
  },
  {
    id: 'personal',
    family: 'non-code',
    label: 'Home & personal',
    description: 'household, family, travel, study, and everything off the clock',
  },
  {
    id: 'practice',
    family: 'universal',
    label: 'Ways of working',
    description: 'generic procedures — plan it, build it, critique it, keep it safe',
  },
  {
    id: 'other',
    family: 'universal',
    label: 'Everything else',
    description: 'recipes that fit no single shelf',
  },
];

/**
 * Shelf groups. `universal` categories hold recipes that are about no
 * particular subject, so they sit outside the code / non-code split rather
 * than being forced into one side of it.
 */
export const CRAFTBOOK_CATEGORY_FAMILY_META: ReadonlyArray<{
  id: CraftbookCategoryFamily;
  label: string;
}> = [
  { id: 'universal', label: 'Any work' },
  { id: 'code', label: 'Code' },
  { id: 'non-code', label: 'Non-code' },
];

/**
 * Tags that say nothing about subject matter — presentation flags, cadence
 * hints, and the near-universal `gallery` marker — so they never sway a score.
 */
const NEUTRAL_TAGS = new Set([
  'gallery',
  'recommended',
  'night-shift',
  'batch',
  'maintenance-review',
  'workflow',
  'checklist',
  'brief',
  'content',
  'assets',
  'collection',
  'recurring',
  'cadence',
]);

/**
 * Per-category tag weights. `strong` tags name the category on their own;
 * `weak` tags only tip a book that is already leaning that way, which is what
 * keeps shared vocabulary (`review`, `report`, `data`, `release`, `audit`)
 * from dragging unrelated recipes onto a code shelf.
 */
const CATEGORY_TAGS: Record<
  Exclude<CraftbookCategory, 'other' | 'practice'>,
  { strong: readonly string[]; weak: readonly string[] }
> = {
  'code-review': {
    strong: [
      'code-review',
      'pr-review',
      'pull-request',
      'appsec',
      'sast',
      'vulnerability',
      'supply-chain',
      'threat-model',
      'stride',
      'security',
      'dependencies',
      'accessibility',
      'a11y',
      'wcag',
    ],
    weak: ['audit', 'review', 'diff', 'github', 'guardrail', 'safety', 'integrity', 'drift', 'pr'],
  },
  'code-quality': {
    strong: [
      'testing',
      'tests',
      'test-gaps',
      'tdd',
      'regression',
      'regression-test',
      'coverage',
      'qa',
      'manual-test',
      'smoke-test',
      'playwright',
      'refactor',
      'refactoring',
      'technical-debt',
      'code-quality',
      'maintainability',
      'debugging',
      'bug-fix',
      'root-cause',
      'codemod',
      'profiling',
      'type-safety',
      'strict',
    ],
    weak: [
      'debug',
      'quality',
      'performance',
      'optimization',
      'speed',
      'benchmark',
      'cleanup',
      'compatibility',
      'upgrade',
      'rewrite',
      'investigation',
      'diagnosis',
    ],
  },
  'code-release': {
    strong: [
      'release',
      'changelog',
      'release-notes',
      'keep-a-changelog',
      'semver',
      'versioning',
      'deploy',
      'deployment',
      'ci',
      'cd',
      'devops',
      'github-actions',
      'docker',
      'container',
      'dockerfile',
      'rollout',
      'canary',
      'progressive-delivery',
      'feature-flag',
      'kill-switch',
      'rollback',
      'hotfix',
      'whats-new',
      'go-no-go',
      'ship-readiness',
      'pre-flight',
      'bump',
    ],
    weak: [
      'launch',
      'patch',
      'toggle',
      'signing',
      'production',
      'readiness',
      'packaging',
      'pipeline',
      'tagging',
      'build',
      'version',
    ],
  },
  'code-ops': {
    strong: [
      'incident',
      'oncall',
      'sre',
      'monitoring',
      'alerting',
      'alerts',
      'runbook',
      'outage',
      'postmortem',
      'status-page',
      'reliability',
      'resilience',
      'failure-modes',
      'blameless',
      'cron',
      'scheduled-job',
    ],
    weak: [
      'ops',
      'escalation',
      'recovery',
      'drill',
      'log',
      'polling',
      'backup',
      'scheduled',
      'maintenance',
    ],
  },
  'code-data': {
    strong: [
      'api',
      'rest',
      'graphql',
      'grpc',
      'protobuf',
      'rpc',
      'openapi',
      'sql',
      'database',
      'etl',
      'webhook',
      'http',
      'api-client',
      'indexes',
      'query-tuning',
      'scraping',
      'parser',
      'dsl',
      'grammar',
      'lexer',
      'ast',
      'queue',
      'worker',
      'consumer',
      'state-machine',
      'fsm',
      'regex',
      'regexp',
      'schema',
    ],
    weak: [
      'data',
      'integration',
      'ingest',
      'transform',
      'convert',
      'csv',
      'join',
      'merge',
      'reconcile',
      'migration',
      'export',
      'import',
      'routing',
      'dictionary',
      'metadata',
      'query',
      'wrangling',
      'cleaning',
      'pattern',
      'string-matching',
      'validation',
      'data-entry',
      'yaml',
    ],
  },
  'code-docs': {
    strong: ['documentation', 'docs', 'technical-writing', 'glossary', 'design-doc', 'rfc'],
    weak: ['reference', 'spec', 'walkthrough', 'definitions'],
  },
  'code-build': {
    strong: [
      'backend',
      'frontend',
      'web-app',
      'pwa',
      'service-worker',
      'scaffold',
      'cli',
      'command-line',
      'terminal',
      'argv',
      'javascript',
      'typescript',
      'css',
      'html',
      'crud',
      'localstorage',
      'browser-extension',
      'chrome',
      'manifest-v3',
      'popup',
      'widget',
      'embeddable',
      'web-component',
      'custom-element',
      'shadow-dom',
      'module',
      'auth',
      'authentication',
      'login',
      'booking',
      'checkout',
      'forms',
      'wizard',
      'multi-step',
      'game',
      'arcade',
      'puzzle',
      'idle',
      'incremental',
      'clicker',
      'game-jam',
      'micro-game',
      'board-game',
      'turn-based',
      'multiscreen',
      'physics',
      'simulation',
      'particles',
      'gamedev',
      'datapack',
      'minecraft',
      'mod',
      'responsive',
      'srcset',
      'website',
      'static-site',
      'personal-site',
      'portfolio',
      'landing-page',
      'landing',
      'code',
      'sdk',
      'library',
      'architecture',
    ],
    weak: [
      'codebase',
      'ecommerce',
      'engineering',
      'interactive',
      'browser',
      'offline',
      'installable',
      'grid',
      'logic',
      'juice',
      'polish',
      'showcase',
      'admin',
      'session',
      'config',
      'bootstrap',
      'setup',
      'iteration',
      'tooling',
      'tool',
      'script',
      'scripting',
      'automation',
      'app',
      'pages',
      'package',
      'component',
      'server',
      'diagram',
      'flowchart',
      'mermaid',
      'tiles',
      'favicon',
      'developer',
    ],
  },
  media: {
    strong: [
      'video',
      'audio',
      'images',
      'image-generation',
      'photo',
      'photos',
      'tts',
      'text-to-speech',
      'stt',
      'speech-to-text',
      'podcast',
      'narration',
      'music',
      'transcript',
      'transcription',
      'subtitles',
      'srt',
      'vtt',
      'audiobook',
      'voiceover',
      'voice',
      'animation',
      'mp4',
      'animated-gif',
      'gif',
      'footage',
      'reel',
      'clip',
      'highlight-reel',
      'album',
      'captions',
      'thumbnails',
      'storyboard',
      'shots',
      'preproduction',
      'slideshow',
      'episode',
      'rundown',
      'show',
      'show-notes',
      'shownotes',
      'mastering',
      'ocr',
      'scans',
      'vision',
      'comic',
      'panels',
      'sprite',
      'game-art',
      'atlas',
      'render',
      'camera',
    ],
    weak: [
      'timestamps',
      'resize',
      'perceptual-hash',
      'culling',
      'text-extraction',
      'motion',
      'radio',
      'capture',
      'processing',
      'ad-spot',
      'dedup',
      'clustering',
      'alt-text',
    ],
  },
  design: {
    strong: [
      'design',
      'ux',
      'ui',
      'visual-design',
      'interaction-design',
      'usability',
      'branding',
      'logo',
      'identity',
      'palette',
      'color',
      'design-tokens',
      'theme',
      'icons',
      'design-system',
      'moodboard',
      'visual-direction',
      'print',
      'slides',
      'deck',
      'presentation',
      'pptx',
      'powerpoint',
      'canvas',
      'svg',
      'app-icon',
      'poster',
      'layout',
      'booklet',
      'creative-coding',
      'generative',
      'art',
    ],
    weak: ['visual', 'critique', 'style', 'inspiration', 'docblocks', 'banner', 'hero', 'cards'],
  },
  marketing: {
    strong: [
      'marketing',
      'advertising',
      'ppc',
      'ab-testing',
      'ab-test',
      'seo',
      'meta-tags',
      'open-graph',
      'social',
      'newsletter',
      'conversion',
      'press-release',
      'announcement',
      'sales',
      'leads',
      'pitch',
      'investor',
      'fundraising',
      'case-study',
      'success-story',
      'customer-story',
      'engagement',
      'drip-campaign',
      'twitter',
      'linkedin',
      'instagram',
      'bluesky',
      'youtube',
      'copywriting',
      'pricing',
      'plans',
      'one-pager',
      'thread',
      'post',
    ],
    weak: [
      'launch',
      'communications',
      'news',
      'broadcast',
      'multichannel',
      'copy',
      'tone',
      'brand-voice',
      'html-email',
      'blog',
      'explainer',
      'crm',
    ],
  },
  writing: {
    strong: [
      'writing',
      'editing',
      'editorial',
      'proofreading',
      'long-form',
      'chapter',
      'chapters',
      'memoir',
      'narrative',
      'ebook',
      'book',
      'whitepaper',
      'translation',
      'localization',
      'i18n',
      'multilingual',
      'faq',
      'knowledge-base',
      'help-center',
      'wiki',
      'handbook',
      'story',
      'character',
    ],
    weak: [
      'draft',
      'clarity',
      'consistency',
      'markdown',
      'summary',
      'tldr',
      'executive-summary',
      'digest',
      'minutes',
      'notes',
      'docx',
      'word',
      'pdf',
      'how-to',
      'templates',
      'template',
      'letters',
      'thank-you',
      'correspondence',
      'language',
      'article',
      'document',
      'documents',
      'prose',
    ],
  },
  research: {
    strong: [
      'research',
      'analysis',
      'fact-check',
      'literature-review',
      'competitive-analysis',
      'market',
      'trends',
      'industry',
      'landscape',
      'comparison',
      'decision-matrix',
      'evaluation',
      'statistics',
      'forecast',
      'projection',
      'survey',
      'evidence',
      'due-diligence',
      'synthesis',
      'citations',
      'bibliography',
      'sources',
      'curation',
      'reading-list',
      'learning-path',
      'anomaly',
      'outliers',
      'detection',
      'cohort',
      'retention',
      'churn',
      'time-series',
      'data-viz',
      'chart',
      'charts',
      'visualization',
      'verification',
      'accuracy',
      'corpus',
      'knowledge',
    ],
    weak: [
      'news',
      'feeds',
      'rss',
      'investigation',
      'decision-support',
      'recommendation',
      'systemic',
      'dashboard',
      'bi',
      'insights',
      'trend',
      'classification',
      'ranking',
      'categorization',
      'index',
      'tags',
      'academic',
    ],
  },
  business: {
    strong: [
      'finance',
      'billing',
      'invoicing',
      'invoice',
      'expenses',
      'budget',
      'tax',
      'ledger',
      'receipts',
      'bookkeeping',
      'accounting',
      'subscriptions',
      'spend',
      'contract',
      'agreement',
      'legal',
      'proposal',
      'sow',
      'statement-of-work',
      'client',
      'freelance',
      'hr',
      'onboarding',
      'meeting',
      'meetings',
      'agenda',
      'standup',
      'retrospective',
      'debrief',
      'career',
      'job',
      'job-application',
      'resume',
      'cv',
      'cover-letter',
      'interview',
      'offer',
      'compensation',
      'policy',
      'compliance',
      'insurance',
      'inventory',
      'kpi',
      'scorecard',
      'okr',
      'roadmap',
      'strategy',
      'playbook',
      'procedure',
      'process',
      'executive',
      'board',
    ],
    weak: [
      'report',
      'reporting',
      'metrics',
      'analytics',
      'quarterly',
      'annual',
      'weekly',
      'monthly',
      'daily',
      'planning',
      'plan',
      'team',
      'async',
      'support',
      'feedback',
      'intake',
      'triage',
      'inbox',
      'email',
      'comms',
      'messaging',
      'notifications',
      'status',
      'handoff',
      'tasks',
      'task',
      'action-items',
      'actions',
      'productivity',
      'company',
      'product',
      'ideation',
      'experiment',
      'event',
      'events',
      'calendar',
      'follow-up',
      'approval',
      'catalog',
      'risk',
      'close',
      'governance',
    ],
  },
  personal: {
    strong: [
      'household',
      'home',
      'family',
      'family-history',
      'genealogy',
      'garden',
      'pests',
      'meals',
      'meal',
      'recipes',
      'recipe',
      'grocery',
      'pantry',
      'kitchen',
      'menu',
      'travel',
      'trip',
      'packing',
      'departure',
      'holiday',
      'gifts',
      'celebration',
      'invitation',
      'wedding',
      'fundraiser',
      'donations',
      'fitness',
      'coaching',
      'medical',
      'caregiving',
      'visit',
      'appointment',
      'study',
      'flashcards',
      'exam',
      'education',
      'practice',
      'quiz',
      'almanac',
      'estate',
      'heirloom',
      'binder',
      'smart-home',
      'devices',
      'seasonal',
    ],
    weak: [
      'community',
      'thanks',
      'wrapup',
      'personalized',
      'memory',
      'archive',
      'week',
      'focus',
      'morning',
      'countdown',
      'assessment',
      'games',
      'crossword',
      'ritual',
      'plane',
      'life-binder',
    ],
  },
};

const CATEGORY_WEIGHTS = new Map<CraftbookCategory, Map<string, number>>(
  (Object.entries(CATEGORY_TAGS) as [CraftbookCategory, (typeof CATEGORY_TAGS)['media']][]).map(
    ([category, { strong, weak }]) => {
      const weights = new Map<string, number>();
      for (const tag of weak) weights.set(tag, 1);
      for (const tag of strong) weights.set(tag, 3);
      return [category, weights];
    },
  ),
);

/** Scoring order; a tie goes to the category declared first. */
const SCORING_ORDER: readonly CraftbookCategory[] = [
  'code-review',
  'code-quality',
  'code-release',
  'code-ops',
  'code-data',
  'code-docs',
  'code-build',
  'media',
  'design',
  'marketing',
  'writing',
  'research',
  'business',
  'personal',
];

/**
 * Infer a category from a craftbook's tags. Only used when the catalog item
 * does not declare one — first-party content authors `category` explicitly, so
 * this is the floor under third-party and older manifests rather than the
 * mechanism the shipped shelves rely on.
 */
export function inferCraftbookCategory(tags: readonly string[] | undefined): CraftbookCategory {
  const seen = new Set<string>();
  for (const tag of tags ?? []) {
    const normalized = tag.toLowerCase().trim();
    if (normalized && !NEUTRAL_TAGS.has(normalized)) seen.add(normalized);
  }
  if (seen.size === 0) return 'other';
  let best: CraftbookCategory = 'other';
  let bestScore = 0;
  for (const category of SCORING_ORDER) {
    const weights = CATEGORY_WEIGHTS.get(category)!;
    let score = 0;
    for (const tag of seen) score += weights.get(tag) ?? 0;
    if (score > bestScore) {
      best = category;
      bestScore = score;
    }
  }
  return best;
}

/** The category a craftbook browser should shelve this manifest under. */
export function resolveCraftbookCategory(manifest: {
  category?: CraftbookCategory;
  tags?: readonly string[];
}): CraftbookCategory {
  return manifest.category ?? inferCraftbookCategory(manifest.tags);
}

/** Family lookup for a resolved category, for two-level shelf grouping. */
export function craftbookCategoryFamily(category: CraftbookCategory): CraftbookCategoryFamily {
  return CRAFTBOOK_CATEGORY_META.find((meta) => meta.id === category)?.family ?? 'universal';
}
