/**
 * Screenshot manifest plumbing for the browser UX suite.
 *
 * Every `shot()` writes one PNG to a stable path AND one JSON "part" to
 * `.manifest-parts/`. Per-shot parts (instead of one shared manifest.json that
 * every test appends to) are the only race-free option under parallel workers:
 * distinct shots write distinct files, so there's no read-modify-write contention.
 * A single global teardown then merges every part into `manifest.json` + `INDEX.md`.
 *
 * The manifest is the contract an AI agent or skill enumerates to "look at" a
 * surface by stable key (e.g. `chat/composer`): read manifest.json, filter by
 * area/theme/scope, resolve `relativePath` against this directory, read the PNG.
 */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const _dirname = dirname(fileURLToPath(import.meta.url));
// packages/app/e2e-web/helpers -> packages/app/ux-screenshots
export const SCREENSHOT_DIR = resolve(_dirname, '../../ux-screenshots');
export const PARTS_DIR = join(SCREENSHOT_DIR, '.manifest-parts');

export type ShotScope = 'page' | 'element';
export type ShotTheme = 'light' | 'dark';

export interface ShotEntry {
  /** Stable, AI-addressable key: `${area}/${name}` (+ `-dark` for the dark twin). */
  key: string;
  name: string;
  area: string;
  /** POSIX path relative to ux-screenshots/, e.g. `chat/02-composer.png`. */
  relativePath: string;
  description: string;
  scope: ShotScope;
  /** Selector string used for an element clip (or the stabilization anchor). */
  selector?: string;
  theme: ShotTheme;
  viewport: string;
  /** Selector strings of regions painted over before capture. */
  masked: string[];
  /** Source spec file, for provenance. */
  spec: string;
}

export interface ShotManifest {
  version: 1;
  generatedAt: string;
  /** The fixed instant the browser clock was pinned to (see determinism.ts). */
  clockISO: string;
  defaults: {
    viewport: { width: number; height: number; deviceScaleFactor: number };
    locale: string;
    timezone: string;
  };
  shots: Record<string, ShotEntry>;
}

function partFile(key: string): string {
  // `chat/composer` -> `chat__composer.json`; `-dark` stays in the name.
  return join(PARTS_DIR, `${key.replace(/\//g, '__')}.json`);
}

/** Persist one shot's metadata as a race-free fragment. */
export async function writePart(entry: ShotEntry): Promise<void> {
  await mkdir(PARTS_DIR, { recursive: true });
  await writeFile(partFile(entry.key), JSON.stringify(entry, null, 2), 'utf8');
}

/** Merge every fragment into manifest.json + INDEX.md. Called once in global teardown. */
export async function buildManifest(
  defaults: ShotManifest['defaults'],
  clockISO: string,
): Promise<number> {
  let parts: string[] = [];
  try {
    parts = (await readdir(PARTS_DIR)).filter((f) => f.endsWith('.json'));
  } catch {
    parts = []; // no shots were taken this run
  }
  const entries: ShotEntry[] = [];
  for (const f of parts) {
    try {
      entries.push(JSON.parse(await readFile(join(PARTS_DIR, f), 'utf8')) as ShotEntry);
    } catch {
      /* skip a corrupt fragment rather than fail the whole manifest */
    }
  }
  entries.sort((a, b) => a.relativePath.localeCompare(b.relativePath));

  const manifest: ShotManifest = {
    version: 1,
    generatedAt: new Date().toISOString(),
    clockISO,
    defaults,
    shots: Object.fromEntries(entries.map((e) => [e.key, e])),
  };
  await mkdir(SCREENSHOT_DIR, { recursive: true });
  await writeFile(
    join(SCREENSHOT_DIR, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8',
  );
  await writeFile(join(SCREENSHOT_DIR, 'INDEX.md'), renderIndex(entries), 'utf8');
  return entries.length;
}

function renderIndex(entries: ShotEntry[]): string {
  const byArea = new Map<string, ShotEntry[]>();
  for (const e of entries) {
    const list = byArea.get(e.area) ?? [];
    list.push(e);
    byArea.set(e.area, list);
  }
  const lines: string[] = [
    '# Gezel UX screenshot gallery',
    '',
    'Generated by `pnpm test:e2e:web`. Each frame has a stable key (`area/name`) — see `manifest.json`.',
    '',
  ];
  for (const area of [...byArea.keys()].sort()) {
    lines.push(`## ${area}`, '');
    for (const e of byArea.get(area)!) {
      const badges = [e.scope, e.theme, e.viewport].join(' · ');
      lines.push(`### \`${e.key}\` · ${badges}`);
      lines.push(`![${e.key}](${e.relativePath})`);
      lines.push('');
      lines.push(e.description);
      if (e.selector) lines.push(`\nselector: \`${e.selector}\``);
      if (e.masked.length) lines.push(`\nmasked: ${e.masked.map((m) => `\`${m}\``).join(', ')}`);
      lines.push('');
    }
  }
  return `${lines.join('\n')}\n`;
}
