import {
  GEZEL_VERSION,
  type GezelConfig,
  resolveSandboxCopilot,
  resolveShowWorkInProgressFeatures,
} from '@bendyline/gezel';
import { resolveDefaultProviderName } from '../../providers/default-provider.js';

/**
 * The config fields GET and PUT `/api/config` both return, derived from the
 * stored config alone. One mapper for both responses: the handlers used to
 * build their own copies of this whitelist, and every field one of them
 * forgot came back as its default — the Settings control snapped back the
 * moment it was saved, and the next edit wrote that default to disk.
 *
 * Every `GezelConfigSchema` key is either returned here, served by the
 * handler (credentials, masked), or listed in `CONFIG_RESPONSE_OMITTED` with
 * the reason; `config-view.test.ts` enforces it, so a new config field has to
 * be placed deliberately.
 */
export function configResponseFields(config: GezelConfig): Record<string, unknown> {
  return {
    provider: resolveDefaultProviderName(config),
    generalistMode: config.generalistMode,
    ollamaBaseUrl: config.ollamaBaseUrl,
    autoStartOllama: config.autoStartOllama ?? true,
    ollamaNumCtx: config.ollamaNumCtx,
    ollamaNumPredict: config.ollamaNumPredict,
    ollamaThink: config.ollamaThink,
    ollamaStreamingIdleSec: config.ollamaStreamingIdleSec,
    ollamaPreFirstByteIdleSec: config.ollamaPreFirstByteIdleSec,
    ollamaTurnTimeoutMin: config.ollamaTurnTimeoutMin,
    copilotTurnTimeoutMin: config.copilotTurnTimeoutMin,
    defaultModel: config.defaultModel,
    defaultReasoningEffort: config.defaultReasoningEffort,
    firstRunCompleted: config.firstRunCompleted,
    firstRunInstallError: config.firstRunInstallError,
    meesterGezelId: config.meesterGezelId,
    klerkGezelId: config.klerkGezelId,
    boekwachterGezelId: config.boekwachterGezelId,
    keurmeesterGezelId: config.keurmeesterGezelId,
    keurmeester: config.keurmeester,
    debugMode: config.debugMode === true,
    showAdvancedFeatures: config.showAdvancedFeatures === true,
    showWorkInProgressFeatures: resolveShowWorkInProgressFeatures(
      config.showWorkInProgressFeatures,
      GEZEL_VERSION,
    ),
    resetTemplatesOnStartup: config.resetTemplatesOnStartup === true,
    roleBasedNameOnlyMode: config.roleBasedNameOnlyMode === true,
    showPoppetjes: config.showPoppetjes !== false,
    narrateAssistantReplies: config.narrateAssistantReplies === true,
    narrateProgressUpdates: config.narrateProgressUpdates !== false,
    aiEngagementMode: config.aiEngagementMode ?? 'proactive',
    showSystemTray: config.showSystemTray !== false,
    autoUpdateChecks: config.autoUpdateChecks !== false,
    quitOnClose: config.quitOnClose === true,
    themePref: config.themePref,
    cliShowThinking: config.cliShowThinking !== false,
    cliShowWrites: config.cliShowWrites === true,
    documentExportOptions: config.documentExportOptions,
    inlineSpellChecking: config.inlineSpellChecking !== false,
    inlineGrammarChecking: config.inlineGrammarChecking !== false,
    sidebarSide: config.sidebarSide,
    homeGreetingCollapsed: config.homeGreetingCollapsed === true,
    onboarding: config.onboarding,
    workshopTempo: config.workshopTempo ?? 'bedrijvig',
    nightShift: config.nightShift,
    toolFilterMode: config.toolFilterMode ?? 'always',
    channels: config.channels,
    sandboxCopilot: resolveSandboxCopilot(config.sandboxCopilot),
    fetchUrl: config.fetchUrl,
    webSearch: config.webSearch,
    playwrightHeadless: config.playwrightHeadless !== false,
    projectMru: config.projectMru,
    recentTabs: config.recentTabs,
    cacheBudgetMb: config.cacheBudgetMb,
    providerConcurrency: config.providerConcurrency,
    localEngineIdleTimeoutMs: config.localEngineIdleTimeoutMs,
    localEngineReplicas: config.localEngineReplicas,
    localEngineReplicasMax: config.localEngineReplicasMax,
    modelTuning: config.modelTuning,
    modelTuningProfile: config.modelTuningProfile,
    llamaCppBaseUrl: config.llamaCppBaseUrl,
    llamaCppModelPath: config.llamaCppModelPath,
    llamaCppNumCtx: config.llamaCppNumCtx,
    llamaCppBackendOverride: config.llamaCppBackendOverride,
    llamaCppKvCacheType: config.llamaCppKvCacheType,
    llamaCppFlashAttn: config.llamaCppFlashAttn,
    llamaCppSpecType: config.llamaCppSpecType,
    llamaCppSpecDraftSampling: config.llamaCppSpecDraftSampling,
    llamaCppCpuMoe: config.llamaCppCpuMoe,
    llamaCppNCpuFfn: config.llamaCppNCpuFfn,
    llamaCppMlock: config.llamaCppMlock,
    llamaCppLoadMode: config.llamaCppLoadMode,
    llamaCppLazyMode: config.llamaCppLazyMode,
    llamaCppReasoningPreserve: config.llamaCppReasoningPreserve,
    llamaCppSwaFull: config.llamaCppSwaFull,
    ds4BaseUrl: config.ds4BaseUrl,
    ds4ModelPath: config.ds4ModelPath,
    ds4VisionEncoderPath: config.ds4VisionEncoderPath,
    ds4NumCtx: config.ds4NumCtx,
    ds4SsdStreaming: config.ds4SsdStreaming,
    ds4CacheExpertsGb: config.ds4CacheExpertsGb,
    nativeVision: config.nativeVision,
    mlxBaseUrl: config.mlxBaseUrl,
    mlxModelPath: config.mlxModelPath,
    mlxPackageSpec: config.mlxPackageSpec,
    mlxKvBits: config.mlxKvBits,
    anthropicCli: config.anthropicCli,
    codexCli: config.codexCli,
    imageProvider: config.imageProvider,
    defaultImageModel: config.defaultImageModel,
    imageGenerationConfirmation: config.imageGenerationConfirmation,
    videoProvider: config.videoProvider,
    defaultVideoModel: config.defaultVideoModel,
    videoGenerationConfirmation: config.videoGenerationConfirmation,
    defaultSttModel: config.defaultSttModel,
    microphoneDeviceId: config.microphoneDeviceId,
    microphoneDeviceLabel: config.microphoneDeviceLabel,
    recognition: config.recognition,
    gpuMemoryPolicy: config.gpuMemoryPolicy,
    deviceSafety: config.deviceSafety,
    securityPolicy: config.securityPolicy,
    openaiEndpoints: config.openaiEndpoints,
    gildeUpdates: config.gildeUpdates,
    knowledge: config.knowledge,
    faceRecognition: config.faceRecognition,
    taskReferences: config.taskReferences,
    relevanceModel: config.relevanceModel,
    mediaSearch: config.mediaSearch,
    ambientDashboard: config.ambientDashboard,
    ambientDisplay: config.ambientDisplay,
    autoRecall: config.autoRecall,
    retrieval: config.retrieval,
    summarization: config.summarization,
    promptDrafts: config.promptDrafts,
  };
}

const CREDENTIAL = 'credential — served masked by readCredentialView, never from config.json';
const ENGINE_TUNING =
  'engine tuning read from config.json by its provider; no Settings control reads it back';
const SERVICE_OWNED = 'service-owned state or policy with no Settings control that reads it back';

/**
 * Config keys the response leaves out on purpose, each with its reason.
 * Adding a key here is a decision that no screen needs to read it back.
 */
export const CONFIG_RESPONSE_OMITTED: Readonly<Record<string, string>> = {
  githubToken: CREDENTIAL,
  openaiApiKey: CREDENTIAL,
  openaiOrganization: CREDENTIAL,
  anthropicApiKey: CREDENTIAL,
  googleAiApiKey: CREDENTIAL,
  webhookBearerToken: CREDENTIAL,
  webhookBasicAuth: CREDENTIAL,
  braveSearchApiKey: CREDENTIAL,
  tavilyApiKey: CREDENTIAL,
  githubAuth: 'GitHub sign-in state — served by the GitHub identity routes',
  oauthClients: 'served by /api/oauth-clients',
  hosting: 'supervisor-owned hosting choice',
  service: 'remote daemon URL and bearer token — the token must not be echoed',
  externalFolders: 'owned by /api/folders (moves go through the move worker)',
  sharedProjectId: 'internal id of the shared-library project, resolved by the Store',
  executionDensity: 'legacy field migrated to generalistMode by Store.ensureLayout',
  recognitionProvider: 'served by the /api/recognition routes',
  defaultRecognitionModel: 'served by the /api/recognition routes',
  modelFitness: SERVICE_OWNED,
  fileReviews: SERVICE_OWNED,
  autoDownloadEngines: SERVICE_OWNED,
  engineSignaturePolicy: SERVICE_OWNED,
  pythonRuntime: SERVICE_OWNED,
  providerQueue: SERVICE_OWNED,
  taskRunner: SERVICE_OWNED,
  taskBudget: SERVICE_OWNED,
  stuckStep: SERVICE_OWNED,
  memory: SERVICE_OWNED,
  searchIndex: SERVICE_OWNED,
  digest: SERVICE_OWNED,
  meesterStatus: SERVICE_OWNED,
  growth: SERVICE_OWNED,
  projectNudge: SERVICE_OWNED,
  localEngineMemoryGb: SERVICE_OWNED,
  allowRamSpillover: SERVICE_OWNED,
  llamaCppContextSizing: ENGINE_TUNING,
  modelContextOverrides: ENGINE_TUNING,
  ds4Mtp: ENGINE_TUNING,
  ds4MtpExactSampling: ENGINE_TUNING,
  ds4Dspark: ENGINE_TUNING,
  ds4DsparkModelPath: ENGINE_TUNING,
  llamaCppStreamingIdleSec: ENGINE_TUNING,
  llamaCppPreFirstByteIdleSec: ENGINE_TUNING,
  llamaCppNGpuLayers: ENGINE_TUNING,
  llamaCppNCpuMoe: ENGINE_TUNING,
  llamaCppCacheReuse: ENGINE_TUNING,
  llamaCppThreads: ENGINE_TUNING,
  llamaCppBatchSize: ENGINE_TUNING,
  llamaCppDraftModelPath: ENGINE_TUNING,
  llamaCppSpecDraftNMax: ENGINE_TUNING,
  llamaCppExtraArgs: ENGINE_TUNING,
  llamaCppUbatchSize: ENGINE_TUNING,
  mlxNumCtx: ENGINE_TUNING,
  mlxSpecDraftModelPath: ENGINE_TUNING,
  mlxSpeculativeDecoding: ENGINE_TUNING,
  mlxSpecBlockSize: ENGINE_TUNING,
  mlxPrefillStepSize: ENGINE_TUNING,
  mlxDiskCacheBudgetMb: ENGINE_TUNING,
  llamaCppDiskCacheBudgetMb: ENGINE_TUNING,
  layeredPrefixCache: ENGINE_TUNING,
  mlxSharedBandPrefix: ENGINE_TUNING,
};

/** Keys the handler adds from outside config.json (so the test counts them as covered). */
export const CONFIG_RESPONSE_HANDLER_KEYS = ['remoteServing'] as const;
