// GENERATED by scripts/gen-scorecard-barrel.mjs — do not edit by hand.
// Add a sweep by writing packages/core/src/scorecard/data/runs/<run-id>.json
// (the eval scorecard ingest does this for you), then run `pnpm scorecard:barrel`.
import type { ScorecardDataset } from '../schema.js';

import run_2026_08_09_m4max_llamacpp from './runs/2026-08-09-m4max-llamacpp.json' with {
  type: 'json',
};
import run_2026_08_11_m4max_llamacpp from './runs/2026-08-11-m4max-llamacpp.json' with {
  type: 'json',
};
import run_2026_08_13_m4max_llamacpp from './runs/2026-08-13-m4max-llamacpp.json' with {
  type: 'json',
};
import run_2026_08_14_m4max_llamacpp from './runs/2026-08-14-m4max-llamacpp.json' with {
  type: 'json',
};
import run_2026_08_19_gb10_spark from './runs/2026-08-19-gb10-spark.json' with { type: 'json' };
import run_2026_08_20_mac_apple_m4_max from './runs/2026-08-20-mac-apple-m4-max.json' with {
  type: 'json',
};
import run_2026_08_22_mac_apple_m4_max from './runs/2026-08-22-mac-apple-m4-max.json' with {
  type: 'json',
};
import run_2026_08_25_mac_apple_m4_max from './runs/2026-08-25-mac-apple-m4-max.json' with {
  type: 'json',
};
import run_2026_08_27_win32_amd_ryzen_9_7950x3d_16_core_proces from './runs/2026-08-27-win32-amd-ryzen-9-7950x3d-16-core-proces.json' with {
  type: 'json',
};
import run_2026_08_30_dgx_spark_class from './runs/2026-08-30-dgx-spark-class.json' with {
  type: 'json',
};
import run_2026_08_31_dwarfstar_vs_dense from './runs/2026-08-31-dwarfstar-vs-dense.json' with {
  type: 'json',
};
import run_2026_09_02_ryzen_ai_hx_370_core_productivity from './runs/2026-09-02-ryzen-ai-hx-370-core-productivity.json' with {
  type: 'json',
};
import run_2026_09_03_mac_apple_m2 from './runs/2026-09-03-mac-apple-m2.json' with { type: 'json' };
import run_2026_09_04_win32_amd_ryzen_9_7950x3d_16_core_proces from './runs/2026-09-04-win32-amd-ryzen-9-7950x3d-16-core-proces.json' with {
  type: 'json',
};

/** Every recorded sweep. Merged (and ordered by recency) by ../index.ts. */
export const RUN_SHARDS: ScorecardDataset[] = [
  run_2026_08_09_m4max_llamacpp as unknown as ScorecardDataset,
  run_2026_08_11_m4max_llamacpp as unknown as ScorecardDataset,
  run_2026_08_13_m4max_llamacpp as unknown as ScorecardDataset,
  run_2026_08_14_m4max_llamacpp as unknown as ScorecardDataset,
  run_2026_08_19_gb10_spark as unknown as ScorecardDataset,
  run_2026_08_20_mac_apple_m4_max as unknown as ScorecardDataset,
  run_2026_08_22_mac_apple_m4_max as unknown as ScorecardDataset,
  run_2026_08_25_mac_apple_m4_max as unknown as ScorecardDataset,
  run_2026_08_27_win32_amd_ryzen_9_7950x3d_16_core_proces as unknown as ScorecardDataset,
  run_2026_08_30_dgx_spark_class as unknown as ScorecardDataset,
  run_2026_08_31_dwarfstar_vs_dense as unknown as ScorecardDataset,
  run_2026_09_02_ryzen_ai_hx_370_core_productivity as unknown as ScorecardDataset,
  run_2026_09_03_mac_apple_m2 as unknown as ScorecardDataset,
  run_2026_09_04_win32_amd_ryzen_9_7950x3d_16_core_proces as unknown as ScorecardDataset,
];
