import type {
  HandboekArticle,
  HandboekRenderMode,
  HandboekToc,
  HandboekTocArea,
} from '@bendyline/gezel';
import { createLogger } from '@bendyline/gezel';
import {
  type CuratedArticle,
  HANDBOEK_AREAS,
  HANDBOEK_AREA_TITLES,
  findHandboekContent,
  loadCuratedArticles,
} from './content.js';
import type { HandboekDeviceInfo } from './device.js';
import { type GeneratedSummary, buildGeneratedBody, listGeneratedSummaries } from './generated.js';
import { type HandboekCatalog, expandMacros } from './macros.js';

export type { CuratedArticle } from './content.js';
export { HANDBOEK_AREAS, HANDBOEK_AREA_TITLES, findHandboekContent } from './content.js';
export { siteDeviceInfo } from './device.js';
export type {
  HandboekDeviceInfo,
  HandboekGezelInfo,
  HandboekHardwareInfo,
  HandboekHardwareTier,
  HandboekModelInfo,
} from './device.js';
export { MACROS, expandMacros, parseAttrs } from './macros.js';
export type { HandboekCatalog } from './macros.js';

const log = createLogger('handboek');

export interface HandboekEngineOptions {
  catalog: HandboekCatalog;
  device: HandboekDeviceInfo;
  /** Override the shipped content tree (tests, authoring). */
  contentDir?: string;
}

export interface HandboekArticleOptions {
  mode?: HandboekRenderMode;
}

export interface HandboekEngine {
  toc(): Promise<HandboekToc>;
  article(id: string, opts?: HandboekArticleOptions): Promise<HandboekArticle | null>;
  /**
   * The `how_do_i` surface: score the corpus against a plain-language
   * question and return the best article(s) rendered in `agent` mode
   * (compact, no figures, real install facts kept). Scoring runs over
   * TOC metadata + curated bodies only — cheap — and only the winners
   * pay for macro expansion.
   */
  howDoI(question: string, opts?: { limit?: number }): Promise<HandboekArticle[]>;
}

/**
 * The handboek engine: merges curated articles (shipped from the repo's
 * `docs/handboek/` tree) with autogenerated ones (catalog + role
 * registry), expands the autoannotation macros, and hands back
 * render-ready squisq markdown. Curated ids shadow generated ids.
 *
 * Content is re-read per call — the corpus is a couple dozen small
 * files, and fresh reads keep authoring (edit → refresh) frictionless.
 */
export function createHandboekEngine(opts: HandboekEngineOptions): HandboekEngine {
  const contentDir = opts.contentDir ?? findHandboekContent() ?? undefined;
  if (!contentDir) {
    log.warn('no handboek content tree found — only generated articles will be served');
  }

  const curated = (): CuratedArticle[] => (contentDir ? loadCuratedArticles(contentDir) : []);

  const engine: HandboekEngine = {
    async toc(): Promise<HandboekToc> {
      const curatedArticles = curated();
      const curatedIds = new Set(curatedArticles.map((a) => a.id));
      let generated: GeneratedSummary[] = [];
      try {
        generated = await listGeneratedSummaries(opts.catalog);
      } catch (err) {
        log.warn(`listing generated handboek articles failed: ${String(err)}`);
      }
      const areas: HandboekTocArea[] = HANDBOEK_AREAS.map((area) => {
        const entries = [
          ...curatedArticles
            .filter((a) => a.area === area)
            .map((a) => ({
              id: a.id,
              title: a.title,
              area,
              order: a.order,
              summary: a.summary,
              generated: false,
              siteVisible: a.siteVisible,
            })),
          ...generated
            .filter((g) => g.area === area && !curatedIds.has(g.id))
            .map((g) => ({
              id: g.id,
              title: g.title,
              area,
              order: g.order,
              summary: g.summary,
              generated: true,
              siteVisible: true,
            })),
        ].sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));
        return { area, title: HANDBOEK_AREA_TITLES[area], entries };
      }).filter((a) => a.entries.length > 0);
      return { areas };
    },

    async article(
      id: string,
      articleOpts?: HandboekArticleOptions,
    ): Promise<HandboekArticle | null> {
      const mode = articleOpts?.mode ?? 'app';
      const curatedMatch = curated().find((a) => a.id === id);
      if (curatedMatch) {
        const { markdown, figures } = await expandMacros(curatedMatch.body, {
          mode,
          catalog: opts.catalog,
          device: opts.device,
        });
        return {
          id,
          title: curatedMatch.title,
          area: curatedMatch.area,
          summary: curatedMatch.summary,
          markdown,
          figures,
          generated: false,
          defaultDuration: curatedMatch.defaultDuration,
        };
      }
      let generated: GeneratedSummary[];
      try {
        generated = await listGeneratedSummaries(opts.catalog);
      } catch (err) {
        log.warn(`listing generated handboek articles failed: ${String(err)}`);
        return null;
      }
      const summary = generated.find((g) => g.id === id);
      if (!summary) return null;
      const body = await buildGeneratedBody(opts.catalog, id);
      if (!body) return null;
      const { markdown, figures } = await expandMacros(body, {
        mode,
        catalog: opts.catalog,
        device: opts.device,
      });
      return {
        id,
        title: summary.title,
        area: summary.area,
        summary: summary.summary,
        markdown,
        figures,
        generated: true,
      };
    },

    async howDoI(question, howOpts) {
      const limit = Math.max(1, Math.min(howOpts?.limit ?? 2, 5));
      const terms = tokenize(question);
      if (terms.length === 0) return [];
      const curatedArticles = curated();
      const bodyById = new Map(curatedArticles.map((a) => [a.id, a.body.toLowerCase()]));
      const { areas } = await engine.toc();
      const scored = areas
        .flatMap((a) => a.entries)
        .map((entry) => {
          let score = 0;
          const title = entry.title.toLowerCase();
          const summary = entry.summary?.toLowerCase() ?? '';
          const body = bodyById.get(entry.id) ?? '';
          for (const term of terms) {
            if (title.includes(term)) score += 5;
            if (entry.id.includes(term)) score += 2;
            if (summary.includes(term)) score += 3;
            if (body.includes(term)) score += 1;
          }
          return { entry, score };
        })
        .filter((s) => s.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit);
      const results: HandboekArticle[] = [];
      for (const { entry } of scored) {
        const article = await engine.article(entry.id, { mode: 'agent' });
        if (!article) continue;
        results.push(
          article.markdown.length > MAX_AGENT_MARKDOWN
            ? {
                ...article,
                markdown: `${article.markdown.slice(0, MAX_AGENT_MARKDOWN)}\n\n[truncated — open "${article.title}" in the Handboek for the rest]`,
              }
            : article,
        );
      }
      return results;
    },
  };
  return engine;
}

const MAX_AGENT_MARKDOWN = 7000;

const STOPWORDS = new Set([
  'a',
  'an',
  'and',
  'are',
  'can',
  'do',
  'does',
  'for',
  'how',
  'i',
  'in',
  'is',
  'it',
  'my',
  'of',
  'on',
  'or',
  'the',
  'to',
  'use',
  'what',
  'when',
  'where',
  'which',
  'who',
  'why',
  'with',
  'you',
  'your',
]);

function tokenize(question: string): string[] {
  return [
    ...new Set(
      question
        .toLowerCase()
        .split(/[^a-z0-9-]+/)
        .filter((w) => w.length > 1 && !STOPWORDS.has(w)),
    ),
  ];
}
