import type {
  CraftbookTemplateManifest,
  HandboekArea,
  HandboekTocSubcategory,
  ProjectTypeManifest,
  RoleId,
} from '@bendyline/gezel';
import {
  CRAFTBOOK_CATEGORY_FAMILY_META,
  CRAFTBOOK_CATEGORY_META,
  ROLES,
  resolveCraftbookCategory,
} from '@bendyline/gezel';
import type { HandboekCatalog } from './macros.js';

/**
 * Autogenerated articles: one per craftbook template, one per project
 * type, one per built-in role, plus their index pages. Summaries are
 * listed for the TOC; bodies are built lazily per request and lean on
 * the same macro directives curated articles use — one expansion
 * pipeline covers both.
 *
 * A curated article with the same id always shadows the generated one,
 * which is how role articles gain hand-written leads without the
 * generator having to know about them.
 */
export interface GeneratedSummary {
  id: string;
  area: HandboekArea;
  title: string;
  order: number;
  summary?: string;
  subcategory?: HandboekTocSubcategory;
}

function firstSentence(text: string): string | undefined {
  const s = text.trim().split(/\.\s/)[0]?.replace(/\.$/, '').trim();
  return s ? `${s}.` : undefined;
}

export async function listGeneratedSummaries(
  catalog: HandboekCatalog,
): Promise<GeneratedSummary[]> {
  const out: GeneratedSummary[] = [];

  for (const role of Object.values(ROLES)) {
    out.push({
      id: `role/${role.id}`,
      area: 'gezel-roles',
      title: `The ${role.label}`,
      order: 10,
      summary: role.summary,
    });
  }

  out.push({
    id: 'craftbooks-index',
    area: 'craftbooks',
    title: 'Every craftbook',
    order: 0,
    summary: 'All the step-by-step procedures your crew can follow.',
  });
  const craftbooks = (await catalog.list('craftbook-template'))
    .map((s) => s.manifest as CraftbookTemplateManifest)
    .sort((a, b) => a.name.localeCompare(b.name));
  // Shelved by subject, matching the New Task dialog and the `/do` picker;
  // the family prefix stands in for the grouping the flat list cannot draw.
  for (const book of craftbooks) {
    const category = resolveCraftbookCategory(book);
    const categoryIndex = CRAFTBOOK_CATEGORY_META.findIndex((item) => item.id === category);
    const categoryMeta = CRAFTBOOK_CATEGORY_META[categoryIndex] ?? CRAFTBOOK_CATEGORY_META.at(-1)!;
    const familyLabel = CRAFTBOOK_CATEGORY_FAMILY_META.find(
      (family) => family.id === categoryMeta.family,
    );
    out.push({
      id: `craftbook/${book.id}`,
      area: 'craftbooks',
      title: book.name,
      order: 10,
      summary: firstSentence(book.description),
      subcategory: {
        id: categoryMeta.id,
        title:
          categoryMeta.family === 'universal' || !familyLabel
            ? categoryMeta.label
            : `${familyLabel.label} · ${categoryMeta.label}`,
        order: categoryIndex < 0 ? CRAFTBOOK_CATEGORY_META.length : categoryIndex,
      },
    });
  }

  out.push({
    id: 'project-types-index',
    area: 'project-types',
    title: 'Every project type',
    order: 0,
    summary: 'Ready-made project setups: crew, craftbooks, and toolsets in one.',
  });
  const projectTypes = (await catalog.list('project-type'))
    .map((s) => s.manifest as ProjectTypeManifest)
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const pt of projectTypes) {
    out.push({
      id: `project-type/${pt.id}`,
      area: 'project-types',
      title: pt.name,
      order: 10,
      summary: firstSentence(pt.description),
    });
  }

  return out;
}

/**
 * Build the markdown body (macros unexpanded) for a generated article
 * id, or null when the id isn't one of ours.
 */
export async function buildGeneratedBody(
  catalog: HandboekCatalog,
  id: string,
): Promise<string | null> {
  const roleMatch = /^role\/([a-z-]+)$/.exec(id);
  if (roleMatch && roleMatch[1]! in ROLES) {
    return roleBody(ROLES[roleMatch[1] as RoleId].id);
  }
  if (id === 'craftbooks-index') {
    return [
      '# Every craftbook',
      '',
      'Craftbooks are step-by-step procedures your crew can follow to produce a real deliverable — each one names its steps, who runs them, and the checks a result must pass.',
      '',
      'For a public catalog grouped by kind of work, browse [Craftbooks in the Gezel Gilde](https://gezelgilde.com/craftbooks/).',
      '',
      '::handboek-craftbook-list',
    ].join('\n');
  }
  const bookMatch = /^craftbook\/(.+)$/.exec(id);
  if (bookMatch) {
    const detail = await catalog.get('craftbook-template', bookMatch[1]!);
    if (!detail) return null;
    const manifest = detail.manifest as CraftbookTemplateManifest;
    const parts = [
      `# ${manifest.name}`,
      '',
      manifest.description.trim(),
      '',
      '## How it runs',
      '',
      `::handboek-craftbook-steps{id=${manifest.id}}`,
    ];
    return parts.join('\n');
  }
  if (id === 'project-types-index') {
    const items = (await catalog.list('project-type'))
      .map((s) => s.manifest as ProjectTypeManifest)
      .sort((a, b) => a.name.localeCompare(b.name));
    const lines = [
      '# Every project type',
      '',
      'A project type outfits a whole project for one kind of work: the right crew, craftbooks, toolsets, and schedules, composed into a single installable setup.',
      '',
      'Browse [Project types in the Gezel Gilde](https://gezelgilde.com/toolsets/#project-types) for the public catalog view.',
    ];
    if (items.length > 0) {
      lines.push('', '| Project type | What it sets up |', '| --- | --- |');
      for (const pt of items) {
        lines.push(
          `| [${pt.name}](project-type/${pt.id}) | ${firstSentence(pt.description) ?? ''} |`,
        );
      }
    }
    return lines.join('\n');
  }
  const ptMatch = /^project-type\/(.+)$/.exec(id);
  if (ptMatch) {
    const detail = await catalog.get('project-type', ptMatch[1]!);
    if (!detail) return null;
    const manifest = detail.manifest as ProjectTypeManifest;
    return [
      `# ${manifest.name}`,
      '',
      manifest.description.trim(),
      '',
      `::handboek-project-type-composition{id=${manifest.id}}`,
    ].join('\n');
  }
  return null;
}

/** Fallback role article — curated leads shadow this whole body. */
function roleBody(roleId: RoleId): string {
  const role = ROLES[roleId];
  return [
    `# The ${role.label}`,
    '',
    role.summary,
    '',
    `::handboek-gezel-roster{role=${roleId}}`,
    '',
    '## Their character',
    '',
    `::handboek-role-about{role=${roleId}}`,
    '',
    '## What they can do',
    '',
    `::handboek-role-tools{role=${roleId} scope=default}`,
    '',
    '### On this device',
    '',
    `::handboek-role-tools{role=${roleId} scope=device}`,
    '',
    '### As models grow',
    '',
    `::handboek-role-tools{role=${roleId} scope=tiers}`,
    '',
    '## Craftbooks they run well',
    '',
    `::handboek-craftbook-list{role=${roleId}}`,
  ].join('\n');
}
