/**
 * Kokoro's phoneme token table, shared by every host.
 *
 * Kokoro v1.0 consumes phoneme symbol ids, not text. This table is the model's
 * own vocabulary: it matches the tokenizer published with
 * `onnx-community/Kokoro-82M-v1.0-ONNX` and the `tokens.txt` inside the pinned
 * offline voice pack, so desktop and mobile pronounce a sentence identically.
 * Ids are sparse, so the table is stored id-indexed: the character at position
 * `n` is the symbol with id `n`, and NUL marks an unused id.
 *
 * Generated by scripts/build-kokoro-lexicon.mjs; do not hand-edit.
 */

/** Symbol for each token id; NUL where the id is unused. */
const SYMBOLS_BY_ID =
  '$;:,.!?\0\0\u2014\u2026"()\u201c\u201d \u0303\u02a3\u02a5\u02a6\u02a8\u1d5d\uab67AI\0\0\0\0\0O\0Q\0ST\0\0W\0Y\u1d4aabcdef\0hijklmnopqrstuvwxyz\u0251\u0250\u0252\u00e6\0\0\u03b2\u0254\u0255\u00e7\0\u0256\u00f0\u02a4\u0259\0\u025a\u025b\u025c\0\0\u025f\0\u0261\0\0\0\0\0\0\u0265\0\u0268\u026a\u029d\0\0\0\0\0\0\u026f\u0270\u014b\u0273\u0272\u0274\u00f8\0\u0278\u03b8\u0153\0\0\u0279\0\u027e\u027b\0\u0281\u027d\u0282\u0283\u0288\u02a7\0\u028a\u028b\0\u028c\u0263\u0264\0\u03c7\u028e\0\0\0\u0292\u0294\0\0\0\0\0\0\0\u02c8\u02cc\u02d0\0\0\0\u02b0\0\u02b2\0\0\0\0\u2193\0\u2192\u2197\u2198\0\0\0\u1d7b';

/** Padding token. Kokoro expects one leading and one trailing pad frame. */
export const KOKORO_PAD_TOKEN = 0;

/**
 * Longest phoneme run Kokoro accepts. The voice pack holds 510 style vectors
 * per voice, indexed by phoneme count, and the runtime requires the count to
 * be strictly below that, so 509 is the most that can be spoken at once.
 */
export const KOKORO_MAX_PHONEMES = 509;

const SYMBOL_TO_ID: ReadonlyMap<string, number> = new Map(
  [...SYMBOLS_BY_ID].flatMap((symbol, id) =>
    symbol === '\0' ? [] : [[symbol, id] as [string, number]],
  ),
);

/** Token id for one phoneme symbol, or undefined when the model has no such symbol. */
export function kokoroTokenFor(symbol: string): number | undefined {
  return SYMBOL_TO_ID.get(symbol);
}

/** Every symbol the model understands. Used for validation and tests. */
export function kokoroSymbols(): readonly string[] {
  return [...SYMBOL_TO_ID.keys()];
}
