/**
 * The model-facing description of each gezel tool a phone can offer, exactly
 * as the desktop MCP server registers it. Both hosts read this table, so a
 * model sees the same words on either; profile behaviors such as
 * `mcp.compact-tool-schemas` then shorten them the same way for small models.
 */
export const GEZEL_TOOL_DESCRIPTIONS = {
  ask_user_question:
    'Ask the user a question and end your turn. Call this whenever you\'d otherwise stall waiting on the user — a design choice, a scope confirmation, an approval on something you drafted, a missing asset. The user sees a structured card in chat AND on the Home "Needs your input" panel AND as a count badge on the Home nav, so they WILL see it. Their answer arrives in your next turn as a new user message starting with `[Answer to: …]`. When the answer is bounded (colors, yes/no, pick one of these three), always pass concrete `choices`; the user can still write a free-text note alongside unless `allowWriteIn: false`. For approvals where you\'ve drafted a task or a document, attach `taskRef` (`projectId/num`) or `documentPath` so the user can review the artifact inline without leaving the card.',
  list_gilde:
    'List the gezel templates ("gilde" — the guild roster) bundled with Gezel. Each template has a canonical role and curated about.md. For normal recruitment call ensure_gezel with the role; to force a separate new gezel from an exact template, call create_gezel with templateId.',
  create_task:
    'Create a task in a project. Always starts with status "active" at the first step of its craftbook. Provide either `craftbookId` (a recipe from the catalog) OR inline `steps` (an ad-hoc craftbook embedded in the task). For recurring work, also pass `spawnsCraftbookId` or `spawnsSteps` plus a `cron` expression; for N parallel copies, pass spawn-side steps plus a `fanout` config.',
  advance_task_step:
    'Mark the named step complete and activate the next one (or a specifically-named step). THIS is how you hand off to another gezel — calling this tool automatically opens a fresh session with the new step\'s assignee (or `suggestedGezelId`) and kicks them off on the work. Do NOT just say "ready to hand off" in chat; that does nothing. Call this tool. A SUCCESSFUL call is terminal for this gezel\'s turn: stop immediately and yield; the successor owns all further work. A rejected gate is not terminal — repair the named issue and retry.',
  list_gezels:
    "List every gezel (agent) on the user's team. Each entry includes id, name, and role. Use this to find the right gezel for a task, or to see who needs a change.",
  ensure_gezel:
    "Make sure a gezel exists who can handle a given job (designer, dev, copywriter, …) and return them, creating one if nothing fits. Prefer this over the `list_gezels` → `list_gilde` → `create_gezel` sequence: one fuzzy, idempotent call reuses a good roster match or creates from the matching gilde template. Gezels are shared across projects, so reuse preserves their memory of the user's preferences. Use `create_gezel` only when you explicitly need a separate new gezel, an exact templateId, or a custom about.md.",
  list_projects:
    'List every project. Projects are separate workspaces with their own file tree, artifacts, and chat history. The `default` project is the catch-all.',
  update_project:
    'Update a project — rename, change description, set / clear its external working directory, assign a voorman gezel, set its lifecycle status, rewrite its about.md / missionObjectives.md, or set shared project properties (e.g. `content.language`, the designated language). Pass `workingDir: ""` to clear the external path. Pass `voormanGezelId: ""` to clear the voorman.',
  start_project:
    'Start a fresh project for any build request, from a single-file prototype to a multimodal product. Atomically: creates the project, selects an appropriate lead or crew for the effective execution mode, creates the kickoff task, and hands off its entry step. ONE call replaces the old multi-call setup ritual; preserve the requested deliverable paths and acceptance criteria in `taskDescription`.',
  list_project_gezels:
    "List every gezel available in a project, in two clearly labeled sections: the shared roster pulled into this project and workspace-local gezels such as `@project` derived from AGENTS.md/CLAUDE.md or `.gezel/`. Use this single call to answer 'who is on this project?' or discover a project-local specialist.",
  add_gezel_to_project:
    "Add a gezel to a project's roster explicitly. Most paths auto-add (voorman assignment, opening a session, message_gezel/ask_gezel, task assignment), so reach for this only when you want to pre-populate the team without one of those triggers — e.g. introducing a reviewer who hasn't been pinged yet. Idempotent.",
  message_gezel:
    'Send a message to another gezel (status check, nudge, broadcast, or file handoff). This is async fire-and-forget: it drops the message into their active project session and their reply surfaces automatically in a later turn. After a successful call, END YOUR TURN immediately — remaining alive can keep the recipient parked and occupies a provider slot. Use this for fan-out and ambient updates; emit every fan-out call in the same tool-call batch before ending. For explicit consultations where you need an inline answer before continuing, use `ask_gezel`. For substantial multi-step work, use tasks + `advance_task_step`. Do NOT just say \'I\'ll talk to Maya\' in chat; that does nothing. Call this tool. When the message asks them to produce a long-form file deliverable (a review, a report, an analysis, a written design), pass `expectedDeliverable: { kind: "file", filePath: "<path>" }` — the target will be steered to `write_file` the deliverable and reply with just the path + a short precis, instead of pasting the full text into chat (the matrix #2 squisq-review failure mode).',
  list_dir:
    'List the files and subdirectories at a path in the project. The project root is the default. When this project links other projects, list `..` to discover them and use `../<project-id>/...` to browse one with this same tool.',
  read_file:
    'Read one project-workspace file, optionally only an inclusive line range. This tool never reads the separate artifacts drawer; use read_artifact for artifact inputs. For files over ~200 lines, pass `startLine`/`endLine` from grep_files, outline_file, or an error instead of loading the whole file. Omit both range fields for the backward-compatible full read. Output uses `N→` line gutters for precise edits; the gutter is display-only and is never part of the file. Pass `raw: true` for text without gutters.',
  write_file:
    'Create or overwrite a file in the project. **This is how you write code** (or any workspace file) for the thing the user is building. Do NOT paste a code block into chat and expect the user to save it — that does nothing; call this tool with the full file body. If the user, task, or checker names a workspace deliverable path such as `index.html`, `report.md`, `analysis.md`, `src/solution.mjs`, `bug_report.md`, `docs/...`, or `packages/...`, call `write_file` with that exact path as soon as you have enough input to write the file. Do not write a plan, artifact, draft note, chat code block, alternate filename, or `workspace/<path>` substitute. For scratch notes or analysis material that is not meant to live in the workspace, use `write_artifact` instead. Path is relative to the project root. HTML and JS/TS files are syntax-checked before write — if the inline `<script>` or source body has a parse error, overwriting an existing file is refused and the existing file is left untouched; a broken first-write HTML draft may still be saved so you can read/repair/append instead of starting over. **For binary files (images, PDFs, audio) generated by another tool into the artifacts drawer, use `copy_artifact_to_workspace` instead of read_artifact + write_file.**',
  append_to_file:
    "Append text to the end of an existing file in the project. Use this to continue a `write_file` that ran out of room — wild on local models when the first call's content exceeded the per-turn output budget. Pass the path and ONLY the missing tail (the parts of the file you haven't written yet); the existing content stays. For a brand-new file, prefer `write_file`. Path is relative to the project root.",
  replace_in_file:
    "Make a surgical edit to an existing file by replacing one literal substring with another. **Strongly preferred over `write_file` for editing any file that already exists** — token cost is proportional to the change, not the file size, and you don't risk re-truncating a long file you already wrote correctly. `find` is matched verbatim (no regex). By default the pattern must match exactly once; pass `occurrence: 'all'` to apply blanket renames, or a 1-based index to target a specific match. Returns a unified diff so you can verify what changed. If `find` isn't unique you'll get back an `ambiguous-match` error — re-read the file and use a longer literal substring.",
  replace_lines:
    "Replace an inclusive range of lines in an existing file with new content — the easiest surgical edit when you know *which lines* are wrong (e.g. `read_file` shows `142→` gutters, or `validate`/`write_file` reported a parse error 'at line 142'). You just give `startLine`/`endLine` and the replacement `content`; no need to reproduce an exact `find` string or count diff coordinates. To replace one line, set `startLine === endLine`. To delete lines, pass an empty `content`. **Do NOT include the `N→` line-number gutter in `content`** — that's a display aid, not file text. **Each edit shifts the lines below it**, so line numbers from an earlier `read_file` go stale after the first edit; this tool reports the shift and re-prints the edited region with fresh numbers, so target your next edit from that, not from the original read.",
  list_artifacts:
    'List files in the project artifacts folder, recursively across all subdirectories. Use this when handing work off between gezels — anything a teammate produced will show up here regardless of how deeply they nested it. A task\'s working files live under its own folder, `tasks/<num>/`. Pass `path` to walk one subtree only (large drawers are capped, so scoping is how you see every file in a corpus); pass `recursive: false` for a one-level listing. Returned paths are relative to the artifacts root and can be read as-is — do NOT prefix with "artifacts/".',
  read_artifact:
    'Read one artifact, using a path returned by `list_artifacts`. Paths are relative to the artifact root: use "reports/summary.md", never add "artifacts/" (a legacy redundant prefix is still accepted). Use the same inclusive `startLine`/`endLine` range shape as `read_file`; the older `lines`/`head`/`tail` shapes remain accepted for compatibility. If the exact path is actually a workspace file and `read_file` is authorized, this read is safely rerouted and reports its resolved surface. Use `read_artifacts` for several known artifact paths.',
  write_artifact:
    "Create or update a file in the project's **artifacts** folder — the side drawer for supporting material (reports, plans, analysis, research, scratch notes). **NOT for the app's source code** — use `write_file` for that. Artifacts live in a separate folder so the user can distinguish your working notes from the code/content you ship. When working a task, its working files belong in that task's folder, `tasks/<num>/` (e.g. `tasks/11/outline.md`). Calls that target an existing workspace path are refused unless `force: true` is set; source-code extensions (.tsx, .css, .html, .py, …) outside the canonical `tasks/`/`scripts/`/`tests/`/`mocks/`/`drafts/` folders are automatically redirected into the workspace with `write_file` semantics.",
  list_documents:
    'List files in the shared documents library — cross-project guides every gezel can read (guidelines, mission statements, style guides, policies). Pass { recursive: true } to see inside folders. To find content rather than names, use search_documents.',
  read_document:
    'Read one document from the shared library by path, or a knowledge-catalog article by its knowledge:// URI (from a `search` result with the knowledge source). Office documents (.docx, .pdf, .pptx, .xlsx) come back converted to markdown. Get paths from the library listing, list_documents, or a search_documents match.',
  write_document:
    'Create or update a document in the shared documents library (markdown preferred). Use for durable cross-project knowledge — guidelines, policies, style rules. For knowledge specific to one project, use a folder named after that project (e.g. "acme-site/decisions.md"). Deliverables for the current job belong in the workspace or artifacts, not here.',
  search:
    "Search indexed knowledge by meaning and keywords through one simple surface. Covers the active and linked projects' workspaces, artifacts, and memories, the shared document library, and any installed knowledge catalogs (reference material with citation URIs). Every result carries provenance and an exact path/line when available — open hits with `read_file` (workspace, including `../<project-id>/...` linked paths), `read_artifact` (artifacts), or `read_document` (shared paths and knowledge:// URIs). This is the preferred discovery tool; `grep_files` remains best for exact strings and regular expressions.",
  search_memory:
    'Search agent and project memories using semantic similarity. Returns the most relevant remembered facts, decisions, and context.',
  save_memory:
    'Save an important fact, decision, preference, or context to memory so you can recall it later. Use this when you learn something worth remembering.',
  read_task_notes:
    'Read the chronological feed of timestamped notes for a task (or a specific step). Omit stepId to read the whole task feed across every step. Each entry has an author (a gezel or the user) and was appended at a known time — newest first.',
  write_task_note:
    'Append one focused, dated, attributed note to a task. Prefer many small notes over a long blob — teammates and you will read this feed later. Author is auto-attributed to you.',
  list_tasks:
    'List tasks. Optionally filter by project, status, or assignee gezel id. Sorted newest-updated first.',
  get_task:
    'Get one task by ref (format: `projectId/num`). Returns full detail: status, assignee, every phase, active phase, any cron schedule, parent task.',
  list_scripts:
    'List the scripts available to this gezel: project-scoped scripts plus the read-only STANDARD library packed into the app. Each entry returns its name, one-line description, input fields (with types), and required capabilities. Standard-library entries (mostly `kind: gate` checks like checkFileMinBytes / checkContains / checkHtmlComplete) are the preferred vocabulary for craftbook step gates — reference them with `scope: "standard"` and parameterize via `inputs` instead of writing new scripts.',
  run_installed_script:
    "Run an ALREADY-INSTALLED project script by NAME — one of the scripts `list_scripts` shows, including ops/probe scripts a craftbook installed. Takes a name, never a file path. To run a file you just wrote yourself (e.g. `tools/derive.mjs`), use `run_nodejs_script` — not this. When a task, kickoff, or step tells you to run a named script, THIS is the runner — not `run_package_script` or `run_npx`. Input is validated against the script's meta.inputs. Returns the stamped output, per-call trace summary, and run id. Runs with undeclared capabilities or missing required inputs fail fast.",
  get_script_run:
    'Fetch a persisted ScriptRun by id. Returns the full call trace, stdout/stderr logs, and stamped output for post-hoc inspection.',
} as const satisfies Record<string, string>;
