import XCTest
import WebKit
@testable import App

/// App-hosted tests exercise the actual packaged webview/native boundary.
/// Run on a dedicated test simulator; the GGUF resource is generated by the
/// native bridge test writer, never downloaded or shipped with the app.
final class MobileBridgeTests: XCTestCase {
    @MainActor
    func testPackagedWorkerAndNativeStreamingChat() async throws {
        var webView: WKWebView?
        for _ in 0..<100 {
            webView = UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }
                .flatMap(\.windows).compactMap { $0.rootViewController as? MainViewController }.first?.webView
            if let webView,
               (try? await webView.evaluateJavaScript("Boolean(document.querySelector('[aria-label=\"Primary navigation\"]'))")) as? Bool == true { break }
            try await Task.sleep(nanoseconds: 100_000_000)
        }
        let view = try XCTUnwrap(webView)
        let rendered = try await view.evaluateJavaScript("Boolean(document.querySelector('[aria-label=\"Primary navigation\"]'))") as? Bool
        XCTAssertEqual(rendered, true, "Packaged worker must finish loading the persisted mobile state")
        func attachSnapshot(_ name: String) async throws {
            let attachment = XCTAttachment(image: try await view.takeSnapshot(configuration: nil))
            attachment.name = name
            attachment.lifetime = .keepAlways
            add(attachment)
        }
        try await attachSnapshot("Phone primary navigation")
        let settingsOpened = try await view.callAsyncJavaScript("""
            const shell = document.querySelector('.responsive-app-shell');
            const main = shell.querySelector('main');
            if (shell.dataset.compact === 'true' && !main.hidden) throw new Error('Phone must start with primary navigation');
            const settings = document.querySelector('[data-testid="sidebar-area-settings"]');
            if (!settings?.getClientRects().length) throw new Error('Settings must be visible in primary navigation');
            settings.click();
            for (let attempt = 0; attempt < 100; attempt++) {
                const panel = document.querySelector('.mobile-settings');
                if (panel?.getClientRects().length && !main.hidden) return true;
                await new Promise(resolve => setTimeout(resolve, 100));
            }
            throw new Error('Settings did not open from primary navigation');
            """, arguments: [:], in: nil, contentWorld: .page) as? Bool
        XCTAssertEqual(settingsOpened, true)
        var providerOptions: [String] = []
        for _ in 0..<100 {
            providerOptions = (try await view.evaluateJavaScript("Array.from(document.querySelectorAll('.mobile-models select:first-of-type option')).map(option => option.value)")) as? [String] ?? []
            if providerOptions.contains("apple-foundation-models") { break }
            try await Task.sleep(nanoseconds: 100_000_000)
        }
        XCTAssertTrue(providerOptions.contains("llama-cpp"))
        XCTAssertTrue(providerOptions.contains("apple-foundation-models"), "Native descriptors must reach the actual provider chooser through the packaged worker")
        try await attachSnapshot("Global model Settings")

        let support = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        let root = support.appendingPathComponent("Gezel", isDirectory: true)
        let inventory = root.appendingPathComponent("models.json")
        let prior = try? Data(contentsOf: inventory)
        let stateFile = root.appendingPathComponent("state.json")
        let priorState = try? Data(contentsOf: stateFile)
        let fixture = try XCTUnwrap(Bundle(for: Self.self).url(forResource: "ios-fixture", withExtension: "gguf"))
        let store = try MobileStore(root: root)
        let model = try store.importModel(from: fixture)
        _ = try store.selectModel(id: model.id)
        defer {
            if let priorState { try? priorState.write(to: stateFile, options: .atomic) }
            else { try? FileManager.default.removeItem(at: stateFile) }
            if let prior { try? prior.write(to: inventory, options: .atomic) }
            else { try? FileManager.default.removeItem(at: inventory) }
            try? FileManager.default.removeItem(at: root.appendingPathComponent("models/\(model.id).gguf"))
        }
        let uiResult = try await view.callAsyncJavaScript("""
            const plugin = window.Capacitor.Plugins.GezelMobile;
            const pause = () => new Promise(resolve => setTimeout(resolve, 100));
            const read = async () => JSON.parse((await plugin.readState()).data);
            const until = async (action, description) => {
                for (let attempt = 0; attempt < 600; attempt++) {
                    const value = await action();
                    if (value) return value;
                    const error = document.querySelector('[role="alert"]')?.textContent;
                    if (error) throw new Error(description + ': ' + error);
                    await pause();
                }
                throw new Error('Timed out: ' + description);
            };
            const visible = element => Boolean(element?.getClientRects().length);
            const models = document.querySelector('.mobile-settings .mobile-models');
            const openModels = () => { if (!models.open) models.querySelector('summary').click(); };
            openModels();
            const refresh = Array.from(models.querySelectorAll('button')).find(button => button.textContent === 'Check availability');
            await until(() => visible(refresh) && !refresh.disabled, 'model controls in Settings');
            refresh.click();
            const chooser = Array.from(models.querySelectorAll('label')).find(label => label.textContent.includes('Use a model')).querySelector('select');
            await until(() => document.querySelector('option[value="' + fixtureId + '"]') && !chooser.disabled && Array.from(chooser.options).some(option => option.value === 'llama-cpp' && !option.disabled), 'fixture availability in the model chooser');
            openModels();
            await until(() => visible(chooser), 'visible provider chooser in Settings');
            const appleReady = Array.from(chooser.options).some(option => option.value === 'apple-foundation-models' && !option.disabled);
            const providerId = appleReady ? 'apple-foundation-models' : 'llama-cpp';
            chooser.value = providerId;
            chooser.dispatchEvent(new Event('change', {bubbles:true}));
            await until(async () => (await read()).selectedProviderId === providerId && !chooser.disabled, 'saved UI provider selection');
            const before = await read();
            const sessionId = before.activeSessionId;
            const count = before.sessions.find(session => session.id === sessionId).messages.length;
            const navigation = document.querySelector('[aria-label="Primary navigation"]');
            if (!visible(navigation)) {
                const toggle = Array.from(document.querySelectorAll('.app-compact-navigation button')).find(button => button.textContent === 'Navigation');
                if (!visible(toggle)) throw new Error('Navigation control is missing from Settings');
                toggle.click();
                await until(() => visible(navigation), 'primary navigation from Settings');
            }
            const project = navigation.querySelector('[data-group="projects"] .app-sidebar-subitem');
            if (!visible(project) || !project.textContent.includes(before.project.name)) throw new Error('Saved project is missing from primary navigation');
            project.click();
            const textarea = document.querySelector('textarea');
            await until(() => visible(document.querySelector('.mobile-project')) && visible(textarea), 'project Meester chat');
            if (visible(document.querySelector('.mobile-settings'))) throw new Error('Global Settings remained visible over the project');
            Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(textarea, 'Say hello in one short sentence.');
            textarea.dispatchEvent(new InputEvent('input', {bubbles:true, inputType:'insertText', data:'Say hello in one short sentence.'}));
            await until(() => !document.querySelector('.mobile-send').disabled, 'enabled Send button');
            document.querySelector('form.mobile-composer').requestSubmit();
            const reply = await until(async () => {
                const current = await read();
                const messages = current.sessions.find(session => session.id === sessionId).messages;
                const assistant = messages[count + 1];
                if (assistant?.status === 'error') throw new Error(assistant.error || 'UI generation failed');
                return assistant?.status === 'complete' && assistant.content && assistant.providerId === providerId ? assistant : null;
            }, 'saved UI assistant response');
            await until(() => document.querySelector('.mobile-send') && !chooser.disabled, 'released UI generation');
            return {providerId, text:reply.content};
            """, arguments: ["fixtureId": model.id], in: nil, contentWorld: .page) as? [String: Any]
        XCTAssertFalse((uiResult?["text"] as? String ?? "").isEmpty)
        try await attachSnapshot("Project Meester conversation")
        print("Packaged navigation, Settings provider selection, and saved project conversation:", uiResult?["providerId"] ?? "missing")
        let result = try await view.callAsyncJavaScript("""
            const plugin = window.Capacitor.Plugins.GezelMobile;
            const saved = await plugin.readState();
            if (!saved.data || !JSON.parse(saved.data).sessions) throw new Error('Worker state was not persisted');
            try { await plugin.writeState({data:'unfinished {'}); throw new Error('Invalid JSON was accepted'); }
            catch (error) { if (error.message === 'Invalid JSON was accepted') throw error; }
            if ((await plugin.readState()).data !== saved.data) throw new Error('Invalid write changed saved state');
            const inventory = await plugin.providers();
            const local = inventory.providers.find(item => item.id === 'llama-cpp');
            const apple = inventory.providers.find(item => item.id === 'apple-foundation-models');
            if (local?.availability !== 'available') throw new Error('Selected fixture should be available');
            if (!apple || apple.locality !== 'on-device' || apple.capabilities.tools !== false) throw new Error('Invalid Apple descriptor');
            if (apple.availability === 'available') {
                let appleStreamed = '';
                const appleListener = await plugin.addListener('chatDelta', event => {
                    if (event.requestId === 'apple-smoke') appleStreamed += event.delta;
                });
                const appleResult = await plugin.generate({providerId:'apple-foundation-models',requestId:'apple-smoke',messages:[{role:'user',content:'Say hello.'}],maxTokens:32});
                await appleListener.remove();
                if (!appleResult.text) throw new Error('Available Apple model produced no response');
                if (appleStreamed !== appleResult.text) throw new Error('Apple stream differed from final response');
                const applePending = plugin.generate({providerId:'apple-foundation-models',requestId:'apple-cancel',messages:[{role:'user',content:'Tell a long story about a garden.'}],maxTokens:1024});
                try { await plugin.generate({requestId:'cross-provider-busy',messages:[{role:'user',content:'Hello'}],maxTokens:8}); throw new Error('Providers ran concurrently'); }
                catch (error) { if (error.code !== 'BUSY') throw error; }
                await plugin.cancel({requestId:'apple-cancel'});
                if ((await applePending).stopReason !== 'cancelled') throw new Error('Apple cancellation did not release its session');
            } else {
                if (!apple.reason) throw new Error('Unavailable Apple model must explain why');
                try { await plugin.generate({providerId:'apple-foundation-models',requestId:'apple-unavailable',messages:[{role:'user',content:'Hello'}]}); throw new Error('Unavailable Apple provider silently fell back'); }
                catch (error) { if (error.code !== 'UNAVAILABLE') throw error; }
            }
            try { await plugin.prepareProvider({providerId:'apple-foundation-models'}); throw new Error('Apple preparation should be OS managed'); }
            catch (error) { if (error.code !== 'OS_MANAGED') throw error; }
            let streamed = '';
            const listener = await plugin.addListener('chatDelta', event => {
                if (event.requestId === 'bridge-smoke') streamed += event.delta;
            });
            const result = await plugin.generate({requestId:'bridge-smoke',messages:[{role:'user',content:'Hello'}],maxTokens:8});
            await listener.remove();
            const pending = plugin.generate({requestId:'cancel-smoke',messages:[{role:'user',content:'Hello'}],maxTokens:256});
            await plugin.cancel({requestId:'cancel-smoke'});
            const cancelled = await pending;
            if (cancelled.stopReason !== 'cancelled') throw new Error('Cancellation did not settle generation');
            const reused = await plugin.generate({requestId:'reuse-smoke',messages:[{role:'user',content:'Hello again'}],maxTokens:8});
            if (reused.text !== 'aaaaaaaa') throw new Error('Engine was not reusable after cancellation');
            await plugin.releaseModel();
            await plugin.removeModel({id:fixtureId});
            if ((await plugin.listModels()).selectedModelId) throw new Error('Removing selected model silently selected another');
            if ((await plugin.providers()).providers.find(item=>item.id==='llama-cpp').availability !== 'unavailable') throw new Error('Removed model stayed available');
            return {text:result.text,stopReason:result.stopReason,streamed,appleAvailability:apple.availability,appleReason:apple.reason ?? ''};
            """, arguments: ["fixtureId": model.id], in: nil, contentWorld: .page) as? [String: Any]
        XCTAssertEqual(result?["text"] as? String, "aaaaaaaa")
        XCTAssertEqual(result?["streamed"] as? String, "aaaaaaaa")
        XCTAssertEqual(result?["stopReason"] as? String, "length")
        print("Apple native provider smoke:", result?["appleAvailability"] ?? "missing", result?["appleReason"] ?? "")

        NotificationCenter.default.post(name: UIApplication.didEnterBackgroundNotification, object: nil)
        let background = try await view.callAsyncJavaScript("return (await window.Capacitor.Plugins.GezelMobile.providers()).providers.every(item => item.availability === 'unavailable' && typeof item.reason === 'string' && item.reason.length > 0);", arguments: [:], in: nil, contentWorld: .page) as? Bool
        XCTAssertEqual(background, true)
        NotificationCenter.default.post(name: UIApplication.didBecomeActiveNotification, object: nil)
    }
}
